// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CatalogVersionsRequest struct {
	Component *string `queryParam:"style=form,explode=false,name=component"`
}

func (c *CatalogVersionsRequest) GetComponent() *string {
	if c == nil {
		return nil
	}
	return c.Component
}

type CatalogVersionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CatalogVersionsResponse *shared.CatalogVersionsResponse
}

func (c *CatalogVersionsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CatalogVersionsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CatalogVersionsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CatalogVersionsResponse) GetCatalogVersionsResponse() *shared.CatalogVersionsResponse {
	if c == nil {
		return nil
	}
	return c.CatalogVersionsResponse
}
