// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CatalogComponentVersionsRequest struct {
	Platform *string `queryParam:"style=form,explode=true,name=platform"`
	Nextflow *string `queryParam:"style=form,explode=true,name=nextflow"`
	Fusion   *string `queryParam:"style=form,explode=true,name=fusion"`
	Sched    *string `queryParam:"style=form,explode=true,name=sched"`
	Wave     *string `queryParam:"style=form,explode=true,name=wave"`
	Key      string  `pathParam:"style=simple,explode=false,name=key"`
}

func (c *CatalogComponentVersionsRequest) GetPlatform() *string {
	if c == nil {
		return nil
	}
	return c.Platform
}

func (c *CatalogComponentVersionsRequest) GetNextflow() *string {
	if c == nil {
		return nil
	}
	return c.Nextflow
}

func (c *CatalogComponentVersionsRequest) GetFusion() *string {
	if c == nil {
		return nil
	}
	return c.Fusion
}

func (c *CatalogComponentVersionsRequest) GetSched() *string {
	if c == nil {
		return nil
	}
	return c.Sched
}

func (c *CatalogComponentVersionsRequest) GetWave() *string {
	if c == nil {
		return nil
	}
	return c.Wave
}

func (c *CatalogComponentVersionsRequest) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

type CatalogComponentVersionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CatalogVersionsResponse *shared.CatalogVersionsResponse
}

func (c *CatalogComponentVersionsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CatalogComponentVersionsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CatalogComponentVersionsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CatalogComponentVersionsResponse) GetCatalogVersionsResponse() *shared.CatalogVersionsResponse {
	if c == nil {
		return nil
	}
	return c.CatalogVersionsResponse
}
