// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateAwsCloudCERequest struct {
	// Workspace numeric identifier
	WorkspaceID int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// AWS Cloud compute environment create request
	CreateAwsCloudCERequest shared.CreateAwsCloudCERequest `request:"mediaType=application/json"`
}

func (c *CreateAwsCloudCERequest) GetWorkspaceID() int64 {
	if c == nil {
		return 0
	}
	return c.WorkspaceID
}

func (c *CreateAwsCloudCERequest) GetCreateAwsCloudCERequest() shared.CreateAwsCloudCERequest {
	if c == nil {
		return shared.CreateAwsCloudCERequest{}
	}
	return c.CreateAwsCloudCERequest
}

type CreateAwsCloudCEResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateAwsCloudCEResponse *shared.CreateAwsCloudCEResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (c *CreateAwsCloudCEResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateAwsCloudCEResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateAwsCloudCEResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateAwsCloudCEResponse) GetCreateAwsCloudCEResponse() *shared.CreateAwsCloudCEResponse {
	if c == nil {
		return nil
	}
	return c.CreateAwsCloudCEResponse
}

func (c *CreateAwsCloudCEResponse) GetErrorResponse() *shared.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
