// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateCodeCommitCredentialsRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// CodeCommit credentials create request
	CreateCodeCommitCredentialsRequest shared.CreateCodeCommitCredentialsRequest `request:"mediaType=application/json"`
}

func (c *CreateCodeCommitCredentialsRequest) GetWorkspaceID() *int64 {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}

func (c *CreateCodeCommitCredentialsRequest) GetCreateCodeCommitCredentialsRequest() shared.CreateCodeCommitCredentialsRequest {
	if c == nil {
		return shared.CreateCodeCommitCredentialsRequest{}
	}
	return c.CreateCodeCommitCredentialsRequest
}

type CreateCodeCommitCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateCodeCommitCredentialsResponse *shared.CreateCodeCommitCredentialsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (c *CreateCodeCommitCredentialsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateCodeCommitCredentialsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateCodeCommitCredentialsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateCodeCommitCredentialsResponse) GetCreateCodeCommitCredentialsResponse() *shared.CreateCodeCommitCredentialsResponse {
	if c == nil {
		return nil
	}
	return c.CreateCodeCommitCredentialsResponse
}

func (c *CreateCodeCommitCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
