// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateWorkflowLaunchRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Source Optional workspace numeric identifier
	SourceWorkspaceID *int64 `queryParam:"style=form,explode=true,name=sourceWorkspaceId"`
	// Workflow launch request
	SubmitWorkflowLaunchRequest shared.SubmitWorkflowLaunchRequest `request:"mediaType=application/json"`
}

func (o *CreateWorkflowLaunchRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *CreateWorkflowLaunchRequest) GetSourceWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.SourceWorkspaceID
}

func (o *CreateWorkflowLaunchRequest) GetSubmitWorkflowLaunchRequest() shared.SubmitWorkflowLaunchRequest {
	if o == nil {
		return shared.SubmitWorkflowLaunchRequest{}
	}
	return o.SubmitWorkflowLaunchRequest
}

type CreateWorkflowLaunchResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	SubmitWorkflowLaunchResponse *shared.SubmitWorkflowLaunchResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (o *CreateWorkflowLaunchResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateWorkflowLaunchResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateWorkflowLaunchResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateWorkflowLaunchResponse) GetSubmitWorkflowLaunchResponse() *shared.SubmitWorkflowLaunchResponse {
	if o == nil {
		return nil
	}
	return o.SubmitWorkflowLaunchResponse
}

func (o *CreateWorkflowLaunchResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
