// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateGoogleBatchCERequest struct {
	// Workspace numeric identifier
	WorkspaceID int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Google Batch compute environment create request
	CreateGoogleBatchCERequest shared.CreateGoogleBatchCERequest `request:"mediaType=application/json"`
}

func (c *CreateGoogleBatchCERequest) GetWorkspaceID() int64 {
	if c == nil {
		return 0
	}
	return c.WorkspaceID
}

func (c *CreateGoogleBatchCERequest) GetCreateGoogleBatchCERequest() shared.CreateGoogleBatchCERequest {
	if c == nil {
		return shared.CreateGoogleBatchCERequest{}
	}
	return c.CreateGoogleBatchCERequest
}

type CreateGoogleBatchCEResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateGoogleBatchCEResponse *shared.CreateGoogleBatchCEResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (c *CreateGoogleBatchCEResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateGoogleBatchCEResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateGoogleBatchCEResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateGoogleBatchCEResponse) GetCreateGoogleBatchCEResponse() *shared.CreateGoogleBatchCEResponse {
	if c == nil {
		return nil
	}
	return c.CreateGoogleBatchCEResponse
}

func (c *CreateGoogleBatchCEResponse) GetErrorResponse() *shared.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
