// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateManagedCredentialsRequest struct {
	// Managed Identity numeric identifier
	ManagedIdentityID int64 `pathParam:"style=simple,explode=false,name=managedIdentityId"`
	// Organization numeric identifier
	OrgID *int64 `queryParam:"style=form,explode=true,name=orgId"`
	// User numeric identifier
	UserID *int64 `queryParam:"style=form,explode=true,name=userId"`
	// Managed Credentials create request
	CreateManagedCredentialsRequest shared.CreateManagedCredentialsRequest `request:"mediaType=application/json"`
}

func (c *CreateManagedCredentialsRequest) GetManagedIdentityID() int64 {
	if c == nil {
		return 0
	}
	return c.ManagedIdentityID
}

func (c *CreateManagedCredentialsRequest) GetOrgID() *int64 {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *CreateManagedCredentialsRequest) GetUserID() *int64 {
	if c == nil {
		return nil
	}
	return c.UserID
}

func (c *CreateManagedCredentialsRequest) GetCreateManagedCredentialsRequest() shared.CreateManagedCredentialsRequest {
	if c == nil {
		return shared.CreateManagedCredentialsRequest{}
	}
	return c.CreateManagedCredentialsRequest
}

type CreateManagedCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateManagedCredentialsResponse *shared.CreateManagedCredentialsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (c *CreateManagedCredentialsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateManagedCredentialsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateManagedCredentialsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateManagedCredentialsResponse) GetCreateManagedCredentialsResponse() *shared.CreateManagedCredentialsResponse {
	if c == nil {
		return nil
	}
	return c.CreateManagedCredentialsResponse
}

func (c *CreateManagedCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
