// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateOrganizationScimTokenRequest struct {
	// Organization numeric identifier
	OrgID int64 `pathParam:"style=simple,explode=false,name=orgId"`
}

func (c *CreateOrganizationScimTokenRequest) GetOrgID() int64 {
	if c == nil {
		return 0
	}
	return c.OrgID
}

type CreateOrganizationScimTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Token created
	CreateScimTokenResponse *shared.CreateScimTokenResponse
}

func (c *CreateOrganizationScimTokenResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrganizationScimTokenResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrganizationScimTokenResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrganizationScimTokenResponse) GetCreateScimTokenResponse() *shared.CreateScimTokenResponse {
	if c == nil {
		return nil
	}
	return c.CreateScimTokenResponse
}
