// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateGiteaCredentialsRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Gitea credentials create request
	CreateGiteaCredentialsRequest shared.CreateGiteaCredentialsRequest `request:"mediaType=application/json"`
}

func (c *CreateGiteaCredentialsRequest) GetWorkspaceID() *int64 {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}

func (c *CreateGiteaCredentialsRequest) GetCreateGiteaCredentialsRequest() shared.CreateGiteaCredentialsRequest {
	if c == nil {
		return shared.CreateGiteaCredentialsRequest{}
	}
	return c.CreateGiteaCredentialsRequest
}

type CreateGiteaCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateGiteaCredentialsResponse *shared.CreateGiteaCredentialsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (c *CreateGiteaCredentialsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateGiteaCredentialsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateGiteaCredentialsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateGiteaCredentialsResponse) GetCreateGiteaCredentialsResponse() *shared.CreateGiteaCredentialsResponse {
	if c == nil {
		return nil
	}
	return c.CreateGiteaCredentialsResponse
}

func (c *CreateGiteaCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
