// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type CreateGitlabCredentialsRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// GitLab credentials create request
	CreateGitlabCredentialsRequest shared.CreateGitlabCredentialsRequest `request:"mediaType=application/json"`
}

func (c *CreateGitlabCredentialsRequest) GetWorkspaceID() *int64 {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}

func (c *CreateGitlabCredentialsRequest) GetCreateGitlabCredentialsRequest() shared.CreateGitlabCredentialsRequest {
	if c == nil {
		return shared.CreateGitlabCredentialsRequest{}
	}
	return c.CreateGitlabCredentialsRequest
}

type CreateGitlabCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateGitlabCredentialsResponse *shared.CreateGitlabCredentialsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (c *CreateGitlabCredentialsResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateGitlabCredentialsResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateGitlabCredentialsResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateGitlabCredentialsResponse) GetCreateGitlabCredentialsResponse() *shared.CreateGitlabCredentialsResponse {
	if c == nil {
		return nil
	}
	return c.CreateGitlabCredentialsResponse
}

func (c *CreateGitlabCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if c == nil {
		return nil
	}
	return c.ErrorResponse
}
