// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DeleteDatasetsRequest struct {
	// Workspace numeric identifier
	WorkspaceID           *int64                       `queryParam:"style=form,explode=true,name=workspaceId"`
	DeleteDatasetsRequest shared.DeleteDatasetsRequest `request:"mediaType=application/json"`
}

func (d *DeleteDatasetsRequest) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}

func (d *DeleteDatasetsRequest) GetDeleteDatasetsRequest() shared.DeleteDatasetsRequest {
	if d == nil {
		return shared.DeleteDatasetsRequest{}
	}
	return d.DeleteDatasetsRequest
}

type DeleteDatasetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DeleteDatasetsResponse *shared.DeleteDatasetsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DeleteDatasetsResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteDatasetsResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteDatasetsResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteDatasetsResponse) GetDeleteDatasetsResponse() *shared.DeleteDatasetsResponse {
	if d == nil {
		return nil
	}
	return d.DeleteDatasetsResponse
}

func (d *DeleteDatasetsResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
