// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DeleteManagedIdentityRequest struct {
	// Managed Identity numeric identifier
	ManagedIdentityID int64 `pathParam:"style=simple,explode=false,name=managedIdentityId"`
	// Organization numeric identifier
	OrgID *int64 `queryParam:"style=form,explode=true,name=orgId"`
	// If deletion of associated Managed Credentials will be blocked by running jobs that depend on them
	Checked *bool `queryParam:"style=form,explode=true,name=checked"`
}

func (d *DeleteManagedIdentityRequest) GetManagedIdentityID() int64 {
	if d == nil {
		return 0
	}
	return d.ManagedIdentityID
}

func (d *DeleteManagedIdentityRequest) GetOrgID() *int64 {
	if d == nil {
		return nil
	}
	return d.OrgID
}

func (d *DeleteManagedIdentityRequest) GetChecked() *bool {
	if d == nil {
		return nil
	}
	return d.Checked
}

type DeleteManagedIdentityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
	// Running jobs block the deletion of this Managed Identity
	DeleteManagedCredentialsConflictResponse *shared.DeleteManagedCredentialsConflictResponse
}

func (d *DeleteManagedIdentityResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteManagedIdentityResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteManagedIdentityResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteManagedIdentityResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}

func (d *DeleteManagedIdentityResponse) GetDeleteManagedCredentialsConflictResponse() *shared.DeleteManagedCredentialsConflictResponse {
	if d == nil {
		return nil
	}
	return d.DeleteManagedCredentialsConflictResponse
}
