// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DeleteWorkflowRequest struct {
	// Workflow string identifier
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Force the deletion even if the workflow is active
	Force *bool `queryParam:"style=form,explode=true,name=force"`
}

func (d *DeleteWorkflowRequest) GetWorkflowID() string {
	if d == nil {
		return ""
	}
	return d.WorkflowID
}

func (d *DeleteWorkflowRequest) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}

func (d *DeleteWorkflowRequest) GetForce() *bool {
	if d == nil {
		return nil
	}
	return d.Force
}

type DeleteWorkflowResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DeleteWorkflowResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteWorkflowResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteWorkflowResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteWorkflowResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
