// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DescribeWorkflowMetricsRequest struct {
	// Workflow string identifier
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
}

func (d *DescribeWorkflowMetricsRequest) GetWorkflowID() string {
	if d == nil {
		return ""
	}
	return d.WorkflowID
}

func (d *DescribeWorkflowMetricsRequest) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}

type DescribeWorkflowMetricsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	GetWorkflowMetricsResponse *shared.GetWorkflowMetricsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DescribeWorkflowMetricsResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DescribeWorkflowMetricsResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DescribeWorkflowMetricsResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DescribeWorkflowMetricsResponse) GetGetWorkflowMetricsResponse() *shared.GetWorkflowMetricsResponse {
	if d == nil {
		return nil
	}
	return d.GetWorkflowMetricsResponse
}

func (d *DescribeWorkflowMetricsResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
