// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DescribeUserRequest struct {
	// User numeric identifier
	UserID int64 `pathParam:"style=simple,explode=false,name=userId"`
}

func (d *DescribeUserRequest) GetUserID() int64 {
	if d == nil {
		return 0
	}
	return d.UserID
}

type DescribeUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DescribeUserResponse *shared.DescribeUserResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DescribeUserResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DescribeUserResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DescribeUserResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DescribeUserResponse) GetDescribeUserResponse() *shared.DescribeUserResponse {
	if d == nil {
		return nil
	}
	return d.DescribeUserResponse
}

func (d *DescribeUserResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
