// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DescribeDataStudioRequest struct {
	// Studio session numeric identifier
	SessionID string `pathParam:"style=simple,explode=false,name=sessionId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
}

func (d *DescribeDataStudioRequest) GetSessionID() string {
	if d == nil {
		return ""
	}
	return d.SessionID
}

func (d *DescribeDataStudioRequest) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}

type DescribeDataStudioResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DataStudioDto *shared.DataStudioDto
	// NotFound, when the Studio is not found or when the API is disabled for the workspace.
	ErrorResponse *shared.ErrorResponse
}

func (d *DescribeDataStudioResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DescribeDataStudioResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DescribeDataStudioResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DescribeDataStudioResponse) GetDataStudioDto() *shared.DataStudioDto {
	if d == nil {
		return nil
	}
	return d.DataStudioDto
}

func (d *DescribeDataStudioResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
