// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type DisableComputeEnvRequest struct {
	// Compute environment string identifier
	ComputeEnvID string `pathParam:"style=simple,explode=false,name=computeEnvId"`
	// Workspace numeric identifier
	WorkspaceID      *int64                   `queryParam:"style=form,explode=true,name=workspaceId"`
	EmptyBodyRequest *shared.EmptyBodyRequest `request:"mediaType=application/json"`
}

func (d *DisableComputeEnvRequest) GetComputeEnvID() string {
	if d == nil {
		return ""
	}
	return d.ComputeEnvID
}

func (d *DisableComputeEnvRequest) GetWorkspaceID() *int64 {
	if d == nil {
		return nil
	}
	return d.WorkspaceID
}

func (d *DisableComputeEnvRequest) GetEmptyBodyRequest() *shared.EmptyBodyRequest {
	if d == nil {
		return nil
	}
	return d.EmptyBodyRequest
}

type DisableComputeEnvResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (d *DisableComputeEnvResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DisableComputeEnvResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DisableComputeEnvResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DisableComputeEnvResponse) GetErrorResponse() *shared.ErrorResponse {
	if d == nil {
		return nil
	}
	return d.ErrorResponse
}
