// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
	"time"
)

type ExportAuditLogsV2CsvRequest struct {
	// Additional attribute values to include in the response (`state` for pre/post image payloads).
	Attributes []shared.AuditLogV2QueryAttribute `queryParam:"style=form,explode=false,name=attributes"`
	// Filter logs with timestamp on or after this date
	TimestampAfterOrEqual *time.Time `queryParam:"style=form,explode=true,name=timestampAfterOrEqual"`
	// Filter logs with timestamp on or before this date
	TimestampBeforeOrEqual *time.Time `queryParam:"style=form,explode=true,name=timestampBeforeOrEqual"`
}

func (e ExportAuditLogsV2CsvRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExportAuditLogsV2CsvRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExportAuditLogsV2CsvRequest) GetAttributes() []shared.AuditLogV2QueryAttribute {
	if e == nil {
		return nil
	}
	return e.Attributes
}

func (e *ExportAuditLogsV2CsvRequest) GetTimestampAfterOrEqual() *time.Time {
	if e == nil {
		return nil
	}
	return e.TimestampAfterOrEqual
}

func (e *ExportAuditLogsV2CsvRequest) GetTimestampBeforeOrEqual() *time.Time {
	if e == nil {
		return nil
	}
	return e.TimestampBeforeOrEqual
}

// #region class-body-exportauditlogsv2csvrequest
// #endregion class-body-exportauditlogsv2csvrequest

type ExportAuditLogsV2CsvResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Bytes []byte
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (e *ExportAuditLogsV2CsvResponse) GetContentType() string {
	if e == nil {
		return ""
	}
	return e.ContentType
}

func (e *ExportAuditLogsV2CsvResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *ExportAuditLogsV2CsvResponse) GetRawResponse() *http.Response {
	if e == nil {
		return nil
	}
	return e.RawResponse
}

func (e *ExportAuditLogsV2CsvResponse) GetBytes() []byte {
	if e == nil {
		return nil
	}
	return e.Bytes
}

func (e *ExportAuditLogsV2CsvResponse) GetErrorResponse() *shared.ErrorResponse {
	if e == nil {
		return nil
	}
	return e.ErrorResponse
}

// #region class-body-exportauditlogsv2csvresponse
// #endregion class-body-exportauditlogsv2csvresponse
