// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type FinishDataLinkUpload1Request struct {
	// Data-link string identifier
	DataLinkID string `pathParam:"style=simple,explode=false,name=dataLinkId"`
	// Path to the destination directory
	DirPath string `pathParam:"style=simple,explode=false,name=dirPath"`
	// Credentials string identifier
	CredentialsID *string `queryParam:"style=form,explode=true,name=credentialsId"`
	// Workspace numeric identifier
	WorkspaceID                          *int64                                      `queryParam:"style=form,explode=true,name=workspaceId"`
	DataLinkFinishMultiPartUploadRequest shared.DataLinkFinishMultiPartUploadRequest `request:"mediaType=application/json"`
}

func (f *FinishDataLinkUpload1Request) GetDataLinkID() string {
	if f == nil {
		return ""
	}
	return f.DataLinkID
}

func (f *FinishDataLinkUpload1Request) GetDirPath() string {
	if f == nil {
		return ""
	}
	return f.DirPath
}

func (f *FinishDataLinkUpload1Request) GetCredentialsID() *string {
	if f == nil {
		return nil
	}
	return f.CredentialsID
}

func (f *FinishDataLinkUpload1Request) GetWorkspaceID() *int64 {
	if f == nil {
		return nil
	}
	return f.WorkspaceID
}

func (f *FinishDataLinkUpload1Request) GetDataLinkFinishMultiPartUploadRequest() shared.DataLinkFinishMultiPartUploadRequest {
	if f == nil {
		return shared.DataLinkFinishMultiPartUploadRequest{}
	}
	return f.DataLinkFinishMultiPartUploadRequest
}

// FinishDataLinkUpload1ResponseBody - FinishDataLinkUpload_1 200 response
type FinishDataLinkUpload1ResponseBody struct {
}

type FinishDataLinkUpload1Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// BadRequest
	ErrorResponse *shared.ErrorResponse
	// FinishDataLinkUpload_1 200 response
	Object *FinishDataLinkUpload1ResponseBody
}

func (f *FinishDataLinkUpload1Response) GetContentType() string {
	if f == nil {
		return ""
	}
	return f.ContentType
}

func (f *FinishDataLinkUpload1Response) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *FinishDataLinkUpload1Response) GetRawResponse() *http.Response {
	if f == nil {
		return nil
	}
	return f.RawResponse
}

func (f *FinishDataLinkUpload1Response) GetErrorResponse() *shared.ErrorResponse {
	if f == nil {
		return nil
	}
	return f.ErrorResponse
}

func (f *FinishDataLinkUpload1Response) GetObject() *FinishDataLinkUpload1ResponseBody {
	if f == nil {
		return nil
	}
	return f.Object
}
