// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type GenerateDownloadURLDataLinkRequest struct {
	// Data-link string identifier
	DataLinkID string `pathParam:"style=simple,explode=false,name=dataLinkId"`
	// File path to download
	FilePath *string `queryParam:"style=form,explode=true,name=filePath"`
	// Credentials identifier
	CredentialsID *string `queryParam:"style=form,explode=true,name=credentialsId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Whether to generate the URL for preview purposes or direct download (default: false)
	Preview *bool `queryParam:"style=form,explode=true,name=preview"`
}

func (o *GenerateDownloadURLDataLinkRequest) GetDataLinkID() string {
	if o == nil {
		return ""
	}
	return o.DataLinkID
}

func (o *GenerateDownloadURLDataLinkRequest) GetFilePath() *string {
	if o == nil {
		return nil
	}
	return o.FilePath
}

func (o *GenerateDownloadURLDataLinkRequest) GetCredentialsID() *string {
	if o == nil {
		return nil
	}
	return o.CredentialsID
}

func (o *GenerateDownloadURLDataLinkRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *GenerateDownloadURLDataLinkRequest) GetPreview() *bool {
	if o == nil {
		return nil
	}
	return o.Preview
}

type GenerateDownloadURLDataLinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DataLinkDownloadURLResponse *shared.DataLinkDownloadURLResponse
	// BadRequest
	ErrorResponse *shared.ErrorResponse
}

func (o *GenerateDownloadURLDataLinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateDownloadURLDataLinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateDownloadURLDataLinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenerateDownloadURLDataLinkResponse) GetDataLinkDownloadURLResponse() *shared.DataLinkDownloadURLResponse {
	if o == nil {
		return nil
	}
	return o.DataLinkDownloadURLResponse
}

func (o *GenerateDownloadURLDataLinkResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
