// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type GenerateRandomWorkflowNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Generated name
	RandomWorkflowNameResponse *shared.RandomWorkflowNameResponse
}

func (o *GenerateRandomWorkflowNameResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerateRandomWorkflowNameResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerateRandomWorkflowNameResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GenerateRandomWorkflowNameResponse) GetRandomWorkflowNameResponse() *shared.RandomWorkflowNameResponse {
	if o == nil {
		return nil
	}
	return o.RandomWorkflowNameResponse
}
