// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type GetAllowedDynamicLabelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Ok
	AllowedDynamicLabelsResponse *shared.AllowedDynamicLabelsResponse
	// Bad Request
	ErrorResponse *shared.ErrorResponse
}

func (o *GetAllowedDynamicLabelsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllowedDynamicLabelsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllowedDynamicLabelsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllowedDynamicLabelsResponse) GetAllowedDynamicLabelsResponse() *shared.AllowedDynamicLabelsResponse {
	if o == nil {
		return nil
	}
	return o.AllowedDynamicLabelsResponse
}

func (o *GetAllowedDynamicLabelsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
