// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type GetWorkflowTaskLogRequest struct {
	// Workflow string identifier
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowId"`
	// Task numeric identifier
	TaskID int64 `pathParam:"style=simple,explode=false,name=taskId"`
	// Workflow log cursor
	Next *string `queryParam:"style=form,explode=true,name=next"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Maximum length in bytes of the log to retrieve
	MaxLength *int64 `queryParam:"style=form,explode=true,name=maxLength"`
}

func (g *GetWorkflowTaskLogRequest) GetWorkflowID() string {
	if g == nil {
		return ""
	}
	return g.WorkflowID
}

func (g *GetWorkflowTaskLogRequest) GetTaskID() int64 {
	if g == nil {
		return 0
	}
	return g.TaskID
}

func (g *GetWorkflowTaskLogRequest) GetNext() *string {
	if g == nil {
		return nil
	}
	return g.Next
}

func (g *GetWorkflowTaskLogRequest) GetWorkspaceID() *int64 {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

func (g *GetWorkflowTaskLogRequest) GetMaxLength() *int64 {
	if g == nil {
		return nil
	}
	return g.MaxLength
}

type GetWorkflowTaskLogResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	WorkflowLogResponse *shared.WorkflowLogResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (g *GetWorkflowTaskLogResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetWorkflowTaskLogResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetWorkflowTaskLogResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetWorkflowTaskLogResponse) GetWorkflowLogResponse() *shared.WorkflowLogResponse {
	if g == nil {
		return nil
	}
	return g.WorkflowLogResponse
}

func (g *GetWorkflowTaskLogResponse) GetErrorResponse() *shared.ErrorResponse {
	if g == nil {
		return nil
	}
	return g.ErrorResponse
}
