// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListOrganizationTeamsRequest struct {
	// Organization numeric identifier
	OrgID int64 `pathParam:"style=simple,explode=false,name=orgId"`
	// Pagination max results
	Max *int `queryParam:"style=form,explode=true,name=max"`
	// Pagination offset
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
	// Filter search parameter
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (o *ListOrganizationTeamsRequest) GetOrgID() int64 {
	if o == nil {
		return 0
	}
	return o.OrgID
}

func (o *ListOrganizationTeamsRequest) GetMax() *int {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *ListOrganizationTeamsRequest) GetOffset() *int {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListOrganizationTeamsRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

type ListOrganizationTeamsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListTeamResponse *shared.ListTeamResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListOrganizationTeamsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListOrganizationTeamsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListOrganizationTeamsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListOrganizationTeamsResponse) GetListTeamResponse() *shared.ListTeamResponse {
	if o == nil {
		return nil
	}
	return o.ListTeamResponse
}

func (o *ListOrganizationTeamsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
