// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListPlatformsRequest struct {
	// Organization numeric identifier
	OrgID *int64 `queryParam:"style=form,explode=true,name=orgId"`
	// Optional workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
}

func (o *ListPlatformsRequest) GetOrgID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *ListPlatformsRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

type ListPlatformsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListPlatformsResponse *shared.ListPlatformsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListPlatformsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListPlatformsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListPlatformsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListPlatformsResponse) GetListPlatformsResponse() *shared.ListPlatformsResponse {
	if o == nil {
		return nil
	}
	return o.ListPlatformsResponse
}

func (o *ListPlatformsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
