// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListOrganizationCollaboratorsRequest struct {
	// Organization numeric identifier
	OrgID int64 `pathParam:"style=simple,explode=false,name=orgId"`
	// Pagination max results
	Max *int `queryParam:"style=form,explode=true,name=max"`
	// Pagination offset
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
	// Filter search parameter
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (l *ListOrganizationCollaboratorsRequest) GetOrgID() int64 {
	if l == nil {
		return 0
	}
	return l.OrgID
}

func (l *ListOrganizationCollaboratorsRequest) GetMax() *int {
	if l == nil {
		return nil
	}
	return l.Max
}

func (l *ListOrganizationCollaboratorsRequest) GetOffset() *int {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListOrganizationCollaboratorsRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

type ListOrganizationCollaboratorsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListMembersResponse *shared.ListMembersResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (l *ListOrganizationCollaboratorsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOrganizationCollaboratorsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOrganizationCollaboratorsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOrganizationCollaboratorsResponse) GetListMembersResponse() *shared.ListMembersResponse {
	if l == nil {
		return nil
	}
	return l.ListMembersResponse
}

func (l *ListOrganizationCollaboratorsResponse) GetErrorResponse() *shared.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
