// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListMountedDataLinkIdsRequest struct {
	// Organization numeric identifier
	OrgID *int64 `queryParam:"style=form,explode=true,name=orgId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Optional Studio status
	Status *string `queryParam:"style=form,explode=true,name=status"`
	// Optional Studio session ID to exclude in the request.
	Exclude *string `queryParam:"style=form,explode=true,name=exclude"`
}

func (o *ListMountedDataLinkIdsRequest) GetOrgID() *int64 {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *ListMountedDataLinkIdsRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *ListMountedDataLinkIdsRequest) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ListMountedDataLinkIdsRequest) GetExclude() *string {
	if o == nil {
		return nil
	}
	return o.Exclude
}

type ListMountedDataLinkIdsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DataStudioMountedLinksResponse *shared.DataStudioMountedLinksResponse
}

func (o *ListMountedDataLinkIdsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListMountedDataLinkIdsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListMountedDataLinkIdsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListMountedDataLinkIdsResponse) GetDataStudioMountedLinksResponse() *shared.DataStudioMountedLinksResponse {
	if o == nil {
		return nil
	}
	return o.DataStudioMountedLinksResponse
}
