// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListPipelineRepositoriesRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
}

func (l *ListPipelineRepositoriesRequest) GetWorkspaceID() *int64 {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

type ListPipelineRepositoriesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListPipelineInfoResponse *shared.ListPipelineInfoResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (l *ListPipelineRepositoriesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPipelineRepositoriesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPipelineRepositoriesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPipelineRepositoriesResponse) GetListPipelineInfoResponse() *shared.ListPipelineInfoResponse {
	if l == nil {
		return nil
	}
	return l.ListPipelineInfoResponse
}

func (l *ListPipelineRepositoriesResponse) GetErrorResponse() *shared.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
