// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListAgentRunsRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Optional search criteria, allowing the keywords `status` (`pending`, `running`, `completed`, `failed`), `agentConfigId`, `workflowId` and `sourcePipelineId`. Free text is not supported.
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Pagination max results
	Max *int `queryParam:"style=form,explode=true,name=max"`
	// Pagination offset
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
}

func (l *ListAgentRunsRequest) GetWorkspaceID() *int64 {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

func (l *ListAgentRunsRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

func (l *ListAgentRunsRequest) GetMax() *int {
	if l == nil {
		return nil
	}
	return l.Max
}

func (l *ListAgentRunsRequest) GetOffset() *int {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListAgentRunsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListAgentRunsResponse *shared.ListAgentRunsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (l *ListAgentRunsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListAgentRunsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListAgentRunsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListAgentRunsResponse) GetListAgentRunsResponse() *shared.ListAgentRunsResponse {
	if l == nil {
		return nil
	}
	return l.ListAgentRunsResponse
}

func (l *ListAgentRunsResponse) GetErrorResponse() *shared.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
