// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListCredentialsRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Platform string identifier
	PlatformID *string `queryParam:"style=form,explode=true,name=platformId"`
}

func (l *ListCredentialsRequest) GetWorkspaceID() *int64 {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

func (l *ListCredentialsRequest) GetPlatformID() *string {
	if l == nil {
		return nil
	}
	return l.PlatformID
}

type ListCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListCredentialsResponse *shared.ListCredentialsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (l *ListCredentialsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListCredentialsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListCredentialsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListCredentialsResponse) GetListCredentialsResponse() *shared.ListCredentialsResponse {
	if l == nil {
		return nil
	}
	return l.ListCredentialsResponse
}

func (l *ListCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
