// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListLabelsRequest struct {
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Pagination max results
	Max *int `queryParam:"style=form,explode=true,name=max"`
	// Pagination offset
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
	// Filter search parameter
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Label type
	Type *shared.LabelType `queryParam:"style=form,explode=true,name=type"`
	// Label default flag
	IsDefault *bool `queryParam:"style=form,explode=true,name=isDefault"`
}

func (o *ListLabelsRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *ListLabelsRequest) GetMax() *int {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *ListLabelsRequest) GetOffset() *int {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListLabelsRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListLabelsRequest) GetType() *shared.LabelType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *ListLabelsRequest) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

type ListLabelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListLabelsResponse *shared.ListLabelsResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListLabelsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListLabelsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListLabelsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListLabelsResponse) GetListLabelsResponse() *shared.ListLabelsResponse {
	if o == nil {
		return nil
	}
	return o.ListLabelsResponse
}

func (o *ListLabelsResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
