// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListPipelinesRequest struct {
	// Additional attribute values to include in the response (`labels`, `optimized` status, `computeEnv`). Returns an empty value (`labels: null`, etc.) if omitted.
	Attributes []shared.PipelineQueryAttribute `queryParam:"style=form,explode=false,name=attributes"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Pagination max results
	Max *int `queryParam:"style=form,explode=true,name=max"`
	// Pagination offset
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
	// Filter search parameter
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Filter visibility parameter
	Visibility *string `queryParam:"style=form,explode=true,name=visibility"`
}

func (o *ListPipelinesRequest) GetAttributes() []shared.PipelineQueryAttribute {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *ListPipelinesRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *ListPipelinesRequest) GetMax() *int {
	if o == nil {
		return nil
	}
	return o.Max
}

func (o *ListPipelinesRequest) GetOffset() *int {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListPipelinesRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListPipelinesRequest) GetVisibility() *string {
	if o == nil {
		return nil
	}
	return o.Visibility
}

type ListPipelinesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListPipelinesResponse *shared.ListPipelinesResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (o *ListPipelinesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListPipelinesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListPipelinesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListPipelinesResponse) GetListPipelinesResponse() *shared.ListPipelinesResponse {
	if o == nil {
		return nil
	}
	return o.ListPipelinesResponse
}

func (o *ListPipelinesResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
