// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type ListDataStudioCheckpointsRequest struct {
	// Studio session numeric identifier
	SessionID string `pathParam:"style=simple,explode=false,name=sessionId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Optional search criteria, allowing free text search on name and keywords: `status`, `before` and `after` for saved date
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Pagination max results
	Max *int `queryParam:"style=form,explode=true,name=max"`
	// Pagination offset
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
}

func (l *ListDataStudioCheckpointsRequest) GetSessionID() string {
	if l == nil {
		return ""
	}
	return l.SessionID
}

func (l *ListDataStudioCheckpointsRequest) GetWorkspaceID() *int64 {
	if l == nil {
		return nil
	}
	return l.WorkspaceID
}

func (l *ListDataStudioCheckpointsRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

func (l *ListDataStudioCheckpointsRequest) GetMax() *int {
	if l == nil {
		return nil
	}
	return l.Max
}

func (l *ListDataStudioCheckpointsRequest) GetOffset() *int {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListDataStudioCheckpointsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DataStudioListCheckpointsResponse *shared.DataStudioListCheckpointsResponse
	// BadRequest
	ErrorResponse *shared.ErrorResponse
}

func (l *ListDataStudioCheckpointsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListDataStudioCheckpointsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListDataStudioCheckpointsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListDataStudioCheckpointsResponse) GetDataStudioListCheckpointsResponse() *shared.DataStudioListCheckpointsResponse {
	if l == nil {
		return nil
	}
	return l.DataStudioListCheckpointsResponse
}

func (l *ListDataStudioCheckpointsResponse) GetErrorResponse() *shared.ErrorResponse {
	if l == nil {
		return nil
	}
	return l.ErrorResponse
}
