// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type PauseActionRequest struct {
	// Action string identifier
	ActionID string `pathParam:"style=simple,explode=false,name=actionId"`
	// Workspace numeric identifier
	WorkspaceID      *int64                   `queryParam:"style=form,explode=true,name=workspaceId"`
	EmptyBodyRequest *shared.EmptyBodyRequest `request:"mediaType=application/json"`
}

func (p *PauseActionRequest) GetActionID() string {
	if p == nil {
		return ""
	}
	return p.ActionID
}

func (p *PauseActionRequest) GetWorkspaceID() *int64 {
	if p == nil {
		return nil
	}
	return p.WorkspaceID
}

func (p *PauseActionRequest) GetEmptyBodyRequest() *shared.EmptyBodyRequest {
	if p == nil {
		return nil
	}
	return p.EmptyBodyRequest
}

type PauseActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (p *PauseActionResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PauseActionResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PauseActionResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PauseActionResponse) GetErrorResponse() *shared.ErrorResponse {
	if p == nil {
		return nil
	}
	return p.ErrorResponse
}
