// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cb7176422d33

package operations

import (
	"net/http"
)

type ResolveCronExpressionRequest struct {
	WorkspaceID *int64            `queryParam:"style=form,explode=false,name=workspaceId"`
	RequestBody map[string]string `request:"mediaType=application/json"`
}

func (r *ResolveCronExpressionRequest) GetWorkspaceID() *int64 {
	if r == nil {
		return nil
	}
	return r.WorkspaceID
}

func (r *ResolveCronExpressionRequest) GetRequestBody() map[string]string {
	if r == nil {
		return map[string]string{}
	}
	return r.RequestBody
}

// ResolveCronExpressionResponseBody - ResolveCronExpression 200 response
type ResolveCronExpressionResponseBody struct {
}

type ResolveCronExpressionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ResolveCronExpression 200 response
	Object *ResolveCronExpressionResponseBody
}

func (r *ResolveCronExpressionResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ResolveCronExpressionResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ResolveCronExpressionResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ResolveCronExpressionResponse) GetObject() *ResolveCronExpressionResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
