// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type StartDataStudioRequest struct {
	// Studio session numeric identifier
	SessionID string `pathParam:"style=simple,explode=false,name=sessionId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// An optional overriding configuration for the studio to be started.
	DataStudioStartRequest shared.DataStudioStartRequest `request:"mediaType=application/json"`
}

func (s *StartDataStudioRequest) GetSessionID() string {
	if s == nil {
		return ""
	}
	return s.SessionID
}

func (s *StartDataStudioRequest) GetWorkspaceID() *int64 {
	if s == nil {
		return nil
	}
	return s.WorkspaceID
}

func (s *StartDataStudioRequest) GetDataStudioStartRequest() shared.DataStudioStartRequest {
	if s == nil {
		return shared.DataStudioStartRequest{}
	}
	return s.DataStudioStartRequest
}

type StartDataStudioResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DataStudioStartResponse *shared.DataStudioStartResponse
	// NotFound, when the studio is not found or when the API is disabled for the workspace
	ErrorResponse *shared.ErrorResponse
}

func (s *StartDataStudioResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *StartDataStudioResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *StartDataStudioResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *StartDataStudioResponse) GetDataStudioStartResponse() *shared.DataStudioStartResponse {
	if s == nil {
		return nil
	}
	return s.DataStudioStartResponse
}

func (s *StartDataStudioResponse) GetErrorResponse() *shared.ErrorResponse {
	if s == nil {
		return nil
	}
	return s.ErrorResponse
}
