// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type UpdateActionRequest struct {
	// Action string identifier
	ActionID string `pathParam:"style=simple,explode=false,name=actionId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Action update request
	UpdateActionRequest shared.UpdateActionRequest `request:"mediaType=application/json"`
}

func (u *UpdateActionRequest) GetActionID() string {
	if u == nil {
		return ""
	}
	return u.ActionID
}

func (u *UpdateActionRequest) GetWorkspaceID() *int64 {
	if u == nil {
		return nil
	}
	return u.WorkspaceID
}

func (u *UpdateActionRequest) GetUpdateActionRequest() shared.UpdateActionRequest {
	if u == nil {
		return shared.UpdateActionRequest{}
	}
	return u.UpdateActionRequest
}

type UpdateActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (u *UpdateActionResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateActionResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateActionResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateActionResponse) GetErrorResponse() *shared.ErrorResponse {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}
