// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type UpdateGithubAppCredentialsRequest struct {
	// Credentials string identifier
	CredentialsID string `pathParam:"style=simple,explode=false,name=credentialsId"`
	// Workspace numeric identifier
	WorkspaceID int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// GitHub App credentials update request
	UpdateGithubAppCredentialsRequest shared.UpdateGithubAppCredentialsRequest `request:"mediaType=application/json"`
}

func (u *UpdateGithubAppCredentialsRequest) GetCredentialsID() string {
	if u == nil {
		return ""
	}
	return u.CredentialsID
}

func (u *UpdateGithubAppCredentialsRequest) GetWorkspaceID() int64 {
	if u == nil {
		return 0
	}
	return u.WorkspaceID
}

func (u *UpdateGithubAppCredentialsRequest) GetUpdateGithubAppCredentialsRequest() shared.UpdateGithubAppCredentialsRequest {
	if u == nil {
		return shared.UpdateGithubAppCredentialsRequest{}
	}
	return u.UpdateGithubAppCredentialsRequest
}

type UpdateGithubAppCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (u *UpdateGithubAppCredentialsResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateGithubAppCredentialsResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateGithubAppCredentialsResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateGithubAppCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}
