// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type UpdateTraceProgressRequest struct {
	// Workflow string identifier.
	WorkflowID string `pathParam:"style=simple,explode=false,name=workflowId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `queryParam:"style=form,explode=true,name=workspaceId"`
	// Trace progress request.
	TraceProgressRequest shared.TraceProgressRequest `request:"mediaType=application/json"`
}

func (o *UpdateTraceProgressRequest) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *UpdateTraceProgressRequest) GetWorkspaceID() *int64 {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *UpdateTraceProgressRequest) GetTraceProgressRequest() shared.TraceProgressRequest {
	if o == nil {
		return shared.TraceProgressRequest{}
	}
	return o.TraceProgressRequest
}

type UpdateTraceProgressResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TraceProgressResponse *shared.TraceProgressResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (o *UpdateTraceProgressResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateTraceProgressResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateTraceProgressResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateTraceProgressResponse) GetTraceProgressResponse() *shared.TraceProgressResponse {
	if o == nil {
		return nil
	}
	return o.TraceProgressResponse
}

func (o *UpdateTraceProgressResponse) GetErrorResponse() *shared.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}
