// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type UpdateServiceAccountRequest struct {
	// Organization numeric identifier
	OrgID                       int64                              `pathParam:"style=simple,explode=false,name=orgId"`
	SaID                        int64                              `pathParam:"style=simple,explode=false,name=saId"`
	UpdateServiceAccountRequest shared.UpdateServiceAccountRequest `request:"mediaType=application/json"`
}

func (u *UpdateServiceAccountRequest) GetOrgID() int64 {
	if u == nil {
		return 0
	}
	return u.OrgID
}

func (u *UpdateServiceAccountRequest) GetSaID() int64 {
	if u == nil {
		return 0
	}
	return u.SaID
}

func (u *UpdateServiceAccountRequest) GetUpdateServiceAccountRequest() shared.UpdateServiceAccountRequest {
	if u == nil {
		return shared.UpdateServiceAccountRequest{}
	}
	return u.UpdateServiceAccountRequest
}

type UpdateServiceAccountResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DescribeServiceAccountResponse *shared.DescribeServiceAccountResponse
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (u *UpdateServiceAccountResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateServiceAccountResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateServiceAccountResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateServiceAccountResponse) GetDescribeServiceAccountResponse() *shared.DescribeServiceAccountResponse {
	if u == nil {
		return nil
	}
	return u.DescribeServiceAccountResponse
}

func (u *UpdateServiceAccountResponse) GetErrorResponse() *shared.ErrorResponse {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}
