// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
	"net/http"
)

type UpdateManagedCredentialsRequest struct {
	// Managed Identity numeric identifier
	ManagedIdentityID int64 `pathParam:"style=simple,explode=false,name=managedIdentityId"`
	// Managed Credentials numeric identifier
	ManagedCredentialsID int64 `pathParam:"style=simple,explode=false,name=managedCredentialsId"`
	// Organization numeric identifier
	OrgID *int64 `queryParam:"style=form,explode=true,name=orgId"`
	// Managed Credentials update request
	UpdateManagedCredentialsRequest shared.UpdateManagedCredentialsRequest `request:"mediaType=application/json"`
}

func (u *UpdateManagedCredentialsRequest) GetManagedIdentityID() int64 {
	if u == nil {
		return 0
	}
	return u.ManagedIdentityID
}

func (u *UpdateManagedCredentialsRequest) GetManagedCredentialsID() int64 {
	if u == nil {
		return 0
	}
	return u.ManagedCredentialsID
}

func (u *UpdateManagedCredentialsRequest) GetOrgID() *int64 {
	if u == nil {
		return nil
	}
	return u.OrgID
}

func (u *UpdateManagedCredentialsRequest) GetUpdateManagedCredentialsRequest() shared.UpdateManagedCredentialsRequest {
	if u == nil {
		return shared.UpdateManagedCredentialsRequest{}
	}
	return u.UpdateManagedCredentialsRequest
}

type UpdateManagedCredentialsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad request
	ErrorResponse *shared.ErrorResponse
}

func (u *UpdateManagedCredentialsResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateManagedCredentialsResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateManagedCredentialsResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateManagedCredentialsResponse) GetErrorResponse() *shared.ErrorResponse {
	if u == nil {
		return nil
	}
	return u.ErrorResponse
}
