resource "seqera_orgs" "my_org" {
  description = "Example org for running GCP centric workflows"
  full_name   = "gcp-example-org"
  name        = "gcp-example-org"
}

resource "seqera_workspace" "my_workspace" {
  description = "An example gcp workspace created with Terraform"
  name        = "example-workspace-gcp"
  full_name   = "Example GCP Workspace"
  org_id      = resource.seqera_orgs.my_org.org_id
  visibility  = "PRIVATE"
}

resource "seqera_datasets" "my_datasets" {
  description  = "Example dataset"
  name         = "terraform-dataset"
  workspace_id = resource.seqera_workspace.my_workspace.id
}

resource "seqera_credential" "gcp_credential" {
  name          = "gcp-terraform-credential"
  provider_type = "google"
  workspace_id  = resource.seqera_workspace.my_workspace.id
  description   = "GCP credentials generated by Terraform"
  keys = {
    google = {
      data = file("${var.service_account_key}")
    }
  }
}

resource "seqera_compute_env" "gcp_batch_compute_env" {
  workspace_id = resource.seqera_workspace.my_workspace.id

  compute_env = {
    name           = "gcp-batch-compute-env"
    description    = "GCP Batch compute environment for bioinformatics workflows"
    platform       = "google-batch"
    credentials_id = resource.seqera_credential.gcp_credential.credentials_id

    config = {
      google_batch = {
        region   = var.gcp_region
        work_dir = var.work_dir
        location = var.gcp_location
      }
    }
  }
}

resource "seqera_pipeline" "hello_world_minimal" {
  description = "Hello world pipeline generated by Terraform"
  name        = "terraform-hello-world-gcp"
  launch = {
    compute_env_id  = resource.seqera_compute_env.gcp_batch_compute_env.compute_env_id
    config_profiles = []
    head_job_cpus   = 6
    pipeline        = "https://github.com/nextflow-io/hello"
    pull_latest     = true
    resume          = false
    revision        = "master"
    work_dir        = var.work_dir
  }
  workspace_id = resource.seqera_workspace.my_workspace.id
}

resource "seqera_workflows" "my_workflows" {
  compute_env_id = resource.seqera_compute_env.gcp_batch_compute_env.compute_env_id
  pipeline       = "nextflow-io/hello"
  work_dir       = var.work_dir
  workspace_id   = resource.seqera_workspace.my_workspace.id
  depends_on     = [seqera_compute_env.gcp_batch_compute_env]
}