// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type ActionLaunchRequestSyntaxParser string

const (
	ActionLaunchRequestSyntaxParserV1 ActionLaunchRequestSyntaxParser = "v1"
	ActionLaunchRequestSyntaxParserV2 ActionLaunchRequestSyntaxParser = "v2"
)

func (e ActionLaunchRequestSyntaxParser) ToPointer() *ActionLaunchRequestSyntaxParser {
	return &e
}
func (e *ActionLaunchRequestSyntaxParser) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "v1":
		fallthrough
	case "v2":
		*e = ActionLaunchRequestSyntaxParser(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ActionLaunchRequestSyntaxParser: %v", v)
	}
}

// ActionLaunchRequest - Launch payload for `seqera_action` Create / Update endpoints.
type ActionLaunchRequest struct {
	ComputeEnvID   *string  `json:"computeEnvId,omitempty"`
	ConfigProfiles []string `json:"configProfiles,omitempty"`
	// Nextflow configuration text
	ConfigText *string `json:"configText,omitempty"`
	// Entry workflow name
	EntryName *string `json:"entryName,omitempty"`
	// Head job CPU allocation
	HeadJobCpus *int `json:"headJobCpus,omitempty"`
	// Head job memory allocation in MB
	HeadJobMemoryMb *int `json:"headJobMemoryMb,omitempty"`
	// Server-generated launch identifier; echoed back on Update.
	ID       *string `json:"id,omitempty"`
	LabelIds []int64 `json:"labelIds,omitempty"`
	// Main script path
	MainScript *string `json:"mainScript,omitempty"`
	// Pipeline parameters text
	ParamsText       *string `json:"paramsText,omitempty"`
	Pipeline         string  `json:"pipeline"`
	PipelineSchemaID *int64  `json:"pipelineSchemaId,omitempty"`
	// Script to run after pipeline execution
	PostRunScript *string `json:"postRunScript,omitempty"`
	// Script to run before pipeline execution
	PreRunScript *string `json:"preRunScript,omitempty"`
	PullLatest   *bool   `default:"false" json:"pullLatest"`
	Resume       *bool   `json:"resume,omitempty"`
	// Pipeline revision
	Revision *string `json:"revision,omitempty"`
	// Custom run name
	RunName *string `json:"runName,omitempty"`
	// Pipeline schema name
	SchemaName   *string                          `json:"schemaName,omitempty"`
	StubRun      *bool                            `default:"false" json:"stubRun"`
	SyntaxParser *ActionLaunchRequestSyntaxParser `json:"syntaxParser,omitempty"`
	// Tower-specific configuration
	TowerConfig *string  `json:"towerConfig,omitempty"`
	UserSecrets []string `json:"userSecrets,omitempty"`
	// Working directory for pipeline execution. Must start with a valid cloud storage prefix (s3://, gs://, az://) or be an absolute local path (/). Do not include a trailing slash — the API strips trailing slashes at launch time, which causes plan diffs. Required for pipelines in private workspaces and personal context; optional for shared workspaces. You can reference the work_dir from your compute environment instead of duplicating the value, e.g. seqera_compute_env.my_ce.compute_env.config.aws_batch.work_dir or seqera_aws_batch_compute_env.my_ce.config.work_dir.
	WorkDir          *string  `json:"workDir"`
	WorkspaceSecrets []string `json:"workspaceSecrets,omitempty"`
}

func (a ActionLaunchRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActionLaunchRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActionLaunchRequest) GetComputeEnvID() *string {
	if a == nil {
		return nil
	}
	return a.ComputeEnvID
}

func (a *ActionLaunchRequest) GetConfigProfiles() []string {
	if a == nil {
		return nil
	}
	return a.ConfigProfiles
}

func (a *ActionLaunchRequest) GetConfigText() *string {
	if a == nil {
		return nil
	}
	return a.ConfigText
}

func (a *ActionLaunchRequest) GetEntryName() *string {
	if a == nil {
		return nil
	}
	return a.EntryName
}

func (a *ActionLaunchRequest) GetHeadJobCpus() *int {
	if a == nil {
		return nil
	}
	return a.HeadJobCpus
}

func (a *ActionLaunchRequest) GetHeadJobMemoryMb() *int {
	if a == nil {
		return nil
	}
	return a.HeadJobMemoryMb
}

func (a *ActionLaunchRequest) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *ActionLaunchRequest) GetLabelIds() []int64 {
	if a == nil {
		return nil
	}
	return a.LabelIds
}

func (a *ActionLaunchRequest) GetMainScript() *string {
	if a == nil {
		return nil
	}
	return a.MainScript
}

func (a *ActionLaunchRequest) GetParamsText() *string {
	if a == nil {
		return nil
	}
	return a.ParamsText
}

func (a *ActionLaunchRequest) GetPipeline() string {
	if a == nil {
		return ""
	}
	return a.Pipeline
}

func (a *ActionLaunchRequest) GetPipelineSchemaID() *int64 {
	if a == nil {
		return nil
	}
	return a.PipelineSchemaID
}

func (a *ActionLaunchRequest) GetPostRunScript() *string {
	if a == nil {
		return nil
	}
	return a.PostRunScript
}

func (a *ActionLaunchRequest) GetPreRunScript() *string {
	if a == nil {
		return nil
	}
	return a.PreRunScript
}

func (a *ActionLaunchRequest) GetPullLatest() *bool {
	if a == nil {
		return nil
	}
	return a.PullLatest
}

func (a *ActionLaunchRequest) GetResume() *bool {
	if a == nil {
		return nil
	}
	return a.Resume
}

func (a *ActionLaunchRequest) GetRevision() *string {
	if a == nil {
		return nil
	}
	return a.Revision
}

func (a *ActionLaunchRequest) GetRunName() *string {
	if a == nil {
		return nil
	}
	return a.RunName
}

func (a *ActionLaunchRequest) GetSchemaName() *string {
	if a == nil {
		return nil
	}
	return a.SchemaName
}

func (a *ActionLaunchRequest) GetStubRun() *bool {
	if a == nil {
		return nil
	}
	return a.StubRun
}

func (a *ActionLaunchRequest) GetSyntaxParser() *ActionLaunchRequestSyntaxParser {
	if a == nil {
		return nil
	}
	return a.SyntaxParser
}

func (a *ActionLaunchRequest) GetTowerConfig() *string {
	if a == nil {
		return nil
	}
	return a.TowerConfig
}

func (a *ActionLaunchRequest) GetUserSecrets() []string {
	if a == nil {
		return nil
	}
	return a.UserSecrets
}

func (a *ActionLaunchRequest) GetWorkDir() *string {
	if a == nil {
		return nil
	}
	return a.WorkDir
}

func (a *ActionLaunchRequest) GetWorkspaceSecrets() []string {
	if a == nil {
		return nil
	}
	return a.WorkspaceSecrets
}
