// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fc49f81f9928

package shared

import (
	"encoding/json"
	"fmt"
)

type ActionQueryAttribute string

const (
	ActionQueryAttributeLabels ActionQueryAttribute = "labels"
)

func (e ActionQueryAttribute) ToPointer() *ActionQueryAttribute {
	return &e
}
func (e *ActionQueryAttribute) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "labels":
		*e = ActionQueryAttribute(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ActionQueryAttribute: %v", v)
	}
}
