// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type ActionTowerActionEvent struct {
	ActionEventType string     `json:"actionEventType"`
	Timestamp       *time.Time `json:"timestamp,omitempty"`
	WorkflowID      *string    `json:"workflowId,omitempty"`
}

func (a ActionTowerActionEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActionTowerActionEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActionTowerActionEvent) GetActionEventType() string {
	if a == nil {
		return ""
	}
	return a.ActionEventType
}

func (a *ActionTowerActionEvent) GetTimestamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.Timestamp
}

func (a *ActionTowerActionEvent) GetWorkflowID() *string {
	if a == nil {
		return nil
	}
	return a.WorkflowID
}
