// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type ActiveConnection struct {
	ID         *int64     `json:"id,omitempty"`
	UserName   *string    `json:"userName,omitempty"`
	Email      *string    `json:"email,omitempty"`
	Avatar     *string    `json:"avatar,omitempty"`
	LastActive *time.Time `json:"lastActive,omitempty"`
}

func (a ActiveConnection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActiveConnection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActiveConnection) GetID() *int64 {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *ActiveConnection) GetUserName() *string {
	if a == nil {
		return nil
	}
	return a.UserName
}

func (a *ActiveConnection) GetEmail() *string {
	if a == nil {
		return nil
	}
	return a.Email
}

func (a *ActiveConnection) GetAvatar() *string {
	if a == nil {
		return nil
	}
	return a.Avatar
}

func (a *ActiveConnection) GetLastActive() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastActive
}
