// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type AuditLogV2QueryAttribute string

const (
	AuditLogV2QueryAttributeState AuditLogV2QueryAttribute = "state"
)

func (e AuditLogV2QueryAttribute) ToPointer() *AuditLogV2QueryAttribute {
	return &e
}
func (e *AuditLogV2QueryAttribute) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "state":
		*e = AuditLogV2QueryAttribute(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuditLogV2QueryAttribute: %v", v)
	}
}
