// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// AWSCredentialProviderType - Cloud provider type (aws)
type AWSCredentialProviderType string

const (
	AWSCredentialProviderTypeAws AWSCredentialProviderType = "aws"
)

func (e AWSCredentialProviderType) ToPointer() *AWSCredentialProviderType {
	return &e
}
func (e *AWSCredentialProviderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws":
		*e = AWSCredentialProviderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AWSCredentialProviderType: %v", v)
	}
}

type AWSCredential struct {
	// Unique identifier for the credential (max 22 characters)
	CredentialsID *string `json:"id,omitempty"`
	// Display name for the credential (max 100 characters)
	Name string `json:"name"`
	// Optional description explaining the purpose of the credential
	Description *string `json:"description,omitempty"`
	// Cloud provider type (aws)
	ProviderType AWSCredentialProviderType `json:"provider"`
	// Base URL for the service
	BaseURL *string `json:"baseUrl,omitempty"`
	// Category of the credential
	Category *string `json:"category,omitempty"`
	// Flag indicating if the credential has been soft-deleted
	Deleted *bool `json:"deleted,omitempty"`
	// Timestamp when the credential was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Timestamp when the credential was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the credential was last updated
	LastUpdated *time.Time      `json:"lastUpdated,omitempty"`
	Keys        AwsSecurityKeys `json:"keys"`
}

func (a AWSCredential) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AWSCredential) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"name", "provider", "keys"}); err != nil {
		return err
	}
	return nil
}

func (o *AWSCredential) GetCredentialsID() *string {
	if o == nil {
		return nil
	}
	return o.CredentialsID
}

func (o *AWSCredential) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AWSCredential) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *AWSCredential) GetProviderType() AWSCredentialProviderType {
	if o == nil {
		return AWSCredentialProviderType("")
	}
	return o.ProviderType
}

func (o *AWSCredential) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}

func (o *AWSCredential) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *AWSCredential) GetDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.Deleted
}

func (o *AWSCredential) GetLastUsed() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUsed
}

func (o *AWSCredential) GetDateCreated() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateCreated
}

func (o *AWSCredential) GetLastUpdated() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUpdated
}

func (o *AWSCredential) GetKeys() AwsSecurityKeys {
	if o == nil {
		return AwsSecurityKeys{}
	}
	return o.Keys
}

type AWSCredentialOutput struct {
	// Unique identifier for the credential (max 22 characters)
	CredentialsID *string `json:"id,omitempty"`
	// Display name for the credential (max 100 characters)
	Name string `json:"name"`
	// Optional description explaining the purpose of the credential
	Description *string `json:"description,omitempty"`
	// Cloud provider type (aws)
	ProviderType AWSCredentialProviderType `json:"provider"`
	// Base URL for the service
	BaseURL *string `json:"baseUrl,omitempty"`
	// Category of the credential
	Category *string `json:"category,omitempty"`
	// Flag indicating if the credential has been soft-deleted
	Deleted *bool `json:"deleted,omitempty"`
	// Timestamp when the credential was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Timestamp when the credential was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the credential was last updated
	LastUpdated *time.Time            `json:"lastUpdated,omitempty"`
	Keys        AwsSecurityKeysOutput `json:"keys"`
}

func (a AWSCredentialOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AWSCredentialOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"name", "provider", "keys"}); err != nil {
		return err
	}
	return nil
}

func (o *AWSCredentialOutput) GetCredentialsID() *string {
	if o == nil {
		return nil
	}
	return o.CredentialsID
}

func (o *AWSCredentialOutput) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AWSCredentialOutput) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *AWSCredentialOutput) GetProviderType() AWSCredentialProviderType {
	if o == nil {
		return AWSCredentialProviderType("")
	}
	return o.ProviderType
}

func (o *AWSCredentialOutput) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}

func (o *AWSCredentialOutput) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *AWSCredentialOutput) GetDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.Deleted
}

func (o *AWSCredentialOutput) GetLastUsed() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUsed
}

func (o *AWSCredentialOutput) GetDateCreated() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateCreated
}

func (o *AWSCredentialOutput) GetLastUpdated() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUpdated
}

func (o *AWSCredentialOutput) GetKeys() AwsSecurityKeysOutput {
	if o == nil {
		return AwsSecurityKeysOutput{}
	}
	return o.Keys
}
