// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// AWSCredentialProviderType - Cloud provider type. Always set by the provider for this resource.
type AWSCredentialProviderType string

const (
	AWSCredentialProviderTypeAws AWSCredentialProviderType = "aws"
)

func (e AWSCredentialProviderType) ToPointer() *AWSCredentialProviderType {
	return &e
}
func (e *AWSCredentialProviderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws":
		*e = AWSCredentialProviderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AWSCredentialProviderType: %v", v)
	}
}

type AWSCredential struct {
	// Unique identifier for the credential (max 22 characters)
	ID *string `json:"id,omitempty"`
	// Alias of `id`. Retained for backwards compatibility with existing customer HCL — both fields hold the same value.
	CredentialsID *string `json:"credentials_id,omitempty"`
	// Display name for the credential. Must be 2-99 characters using only letters, numbers, underscores, and hyphens. No spaces allowed.
	Name string `json:"name"`
	// Cloud provider type. Always set by the provider for this resource.
	ProviderType *AWSCredentialProviderType `default:"aws" json:"provider"`
	// Flag indicating if the credential has been soft-deleted
	Deleted *bool `json:"deleted,omitempty"`
	// Timestamp when the credential was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Timestamp when the credential was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the credential was last updated
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// AWS access key ID. Must start with AKIA (standard) or ASIA (temporary). Required unless assume_role_arn is provided.
	AccessKey *string `json:"access_key,omitempty"`
	// AWS secret access key (sensitive). Must be at least 40 characters. Required unless assume_role_arn is provided.
	SecretKey *string `json:"secret_key,omitempty"`
	// IAM role ARN to assume. Format: arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME. Either this or both access_key and secret_key must be provided.
	AssumeRoleArn *string             `json:"assume_role_arn,omitempty"`
	Mode          *AwsCredentialsMode `json:"mode,omitempty"`
	// External ID for cross-account IAM role assumption. Generated by the platform when useExternalId is enabled.
	ExternalID *string `json:"external_id,omitempty"`
}

func (a AWSCredential) MarshalJSON() ([]byte, error) {
	jsonBytes, err := utils.MarshalJSON(a, "", false)
	if err != nil {
		return nil, err
	}
	out, err := utils.RunJQBytes(jsonBytes, ". + { keys: { accessKey: .access_key, secretKey: .secret_key, assumeRoleArn: .assume_role_arn, mode: .mode, externalId: .external_id } } | del(.access_key, .secret_key, .assume_role_arn, .mode, .external_id, .credentials_id)")
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (a *AWSCredential) UnmarshalJSON(data []byte) error {
	if out, err := utils.RunJQBytes(data, ". + { access_key: .keys.accessKey, secret_key: .keys.secretKey, assume_role_arn: .keys.assumeRoleArn, mode: .keys.mode, external_id: .keys.externalId, credentials_id: .id } | del(.keys)"); err != nil {
		return err
	} else {
		data = out
	}
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AWSCredential) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AWSCredential) GetCredentialsID() *string {
	if a == nil {
		return nil
	}
	return a.CredentialsID
}

func (a *AWSCredential) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AWSCredential) GetProviderType() *AWSCredentialProviderType {
	if a == nil {
		return nil
	}
	return a.ProviderType
}

func (a *AWSCredential) GetDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.Deleted
}

func (a *AWSCredential) GetLastUsed() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsed
}

func (a *AWSCredential) GetDateCreated() *time.Time {
	if a == nil {
		return nil
	}
	return a.DateCreated
}

func (a *AWSCredential) GetLastUpdated() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUpdated
}

func (a *AWSCredential) GetAccessKey() *string {
	if a == nil {
		return nil
	}
	return a.AccessKey
}

func (a *AWSCredential) GetSecretKey() *string {
	if a == nil {
		return nil
	}
	return a.SecretKey
}

func (a *AWSCredential) GetAssumeRoleArn() *string {
	if a == nil {
		return nil
	}
	return a.AssumeRoleArn
}

func (a *AWSCredential) GetMode() *AwsCredentialsMode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *AWSCredential) GetExternalID() *string {
	if a == nil {
		return nil
	}
	return a.ExternalID
}

type AWSCredentialOutput struct {
	// Unique identifier for the credential (max 22 characters)
	ID *string `json:"id,omitempty"`
	// Alias of `id`. Retained for backwards compatibility with existing customer HCL — both fields hold the same value.
	CredentialsID *string `json:"credentials_id,omitempty"`
	// Display name for the credential. Must be 2-99 characters using only letters, numbers, underscores, and hyphens. No spaces allowed.
	Name string `json:"name"`
	// Cloud provider type. Always set by the provider for this resource.
	ProviderType *AWSCredentialProviderType `default:"aws" json:"provider"`
	// Flag indicating if the credential has been soft-deleted
	Deleted *bool `json:"deleted,omitempty"`
	// Timestamp when the credential was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Timestamp when the credential was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the credential was last updated
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// AWS access key ID. Must start with AKIA (standard) or ASIA (temporary). Required unless assume_role_arn is provided.
	AccessKey *string             `json:"access_key,omitempty"`
	Mode      *AwsCredentialsMode `json:"mode,omitempty"`
	// External ID for cross-account IAM role assumption. Generated by the platform when useExternalId is enabled.
	ExternalID *string `json:"external_id,omitempty"`
}

func (a AWSCredentialOutput) MarshalJSON() ([]byte, error) {
	jsonBytes, err := utils.MarshalJSON(a, "", false)
	if err != nil {
		return nil, err
	}
	out, err := utils.RunJQBytes(jsonBytes, ". + { keys: { accessKey: .access_key, secretKey: .secret_key, assumeRoleArn: .assume_role_arn, mode: .mode, externalId: .external_id } } | del(.access_key, .secret_key, .assume_role_arn, .mode, .external_id, .credentials_id)")
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (a *AWSCredentialOutput) UnmarshalJSON(data []byte) error {
	if out, err := utils.RunJQBytes(data, ". + { access_key: .keys.accessKey, secret_key: .keys.secretKey, assume_role_arn: .keys.assumeRoleArn, mode: .keys.mode, external_id: .keys.externalId, credentials_id: .id } | del(.keys)"); err != nil {
		return err
	} else {
		data = out
	}
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AWSCredentialOutput) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AWSCredentialOutput) GetCredentialsID() *string {
	if a == nil {
		return nil
	}
	return a.CredentialsID
}

func (a *AWSCredentialOutput) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AWSCredentialOutput) GetProviderType() *AWSCredentialProviderType {
	if a == nil {
		return nil
	}
	return a.ProviderType
}

func (a *AWSCredentialOutput) GetDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.Deleted
}

func (a *AWSCredentialOutput) GetLastUsed() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsed
}

func (a *AWSCredentialOutput) GetDateCreated() *time.Time {
	if a == nil {
		return nil
	}
	return a.DateCreated
}

func (a *AWSCredentialOutput) GetLastUpdated() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUpdated
}

func (a *AWSCredentialOutput) GetAccessKey() *string {
	if a == nil {
		return nil
	}
	return a.AccessKey
}

func (a *AWSCredentialOutput) GetMode() *AwsCredentialsMode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *AWSCredentialOutput) GetExternalID() *string {
	if a == nil {
		return nil
	}
	return a.ExternalID
}
