// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type AwsSecurityKeys struct {
	CredentialType string  `json:"credentialType"`
	Discriminator  *string `json:"discriminator,omitempty"`
	AccessKey      *string `json:"accessKey,omitempty"`
	SecretKey      *string `json:"secretKey,omitempty"`
	AssumeRoleArn  *string `json:"assumeRoleArn,omitempty"`
}

func (a AwsSecurityKeys) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AwsSecurityKeys) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AwsSecurityKeys) GetCredentialType() string {
	if a == nil {
		return ""
	}
	return a.CredentialType
}

func (a *AwsSecurityKeys) GetDiscriminator() *string {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AwsSecurityKeys) GetAccessKey() *string {
	if a == nil {
		return nil
	}
	return a.AccessKey
}

func (a *AwsSecurityKeys) GetSecretKey() *string {
	if a == nil {
		return nil
	}
	return a.SecretKey
}

func (a *AwsSecurityKeys) GetAssumeRoleArn() *string {
	if a == nil {
		return nil
	}
	return a.AssumeRoleArn
}
