// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AzureSecurityKeys struct {
	Discriminator *string `json:"discriminator,omitempty"`
	BatchName     *string `json:"batchName,omitempty"`
	StorageName   *string `json:"storageName,omitempty"`
	BatchKey      *string `json:"batchKey,omitempty"`
	StorageKey    *string `json:"storageKey,omitempty"`
}

func (o *AzureSecurityKeys) GetDiscriminator() *string {
	if o == nil {
		return nil
	}
	return o.Discriminator
}

func (o *AzureSecurityKeys) GetBatchName() *string {
	if o == nil {
		return nil
	}
	return o.BatchName
}

func (o *AzureSecurityKeys) GetStorageName() *string {
	if o == nil {
		return nil
	}
	return o.StorageName
}

func (o *AzureSecurityKeys) GetBatchKey() *string {
	if o == nil {
		return nil
	}
	return o.BatchKey
}

func (o *AzureSecurityKeys) GetStorageKey() *string {
	if o == nil {
		return nil
	}
	return o.StorageKey
}
