// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// AzureBatchCEComputeConfigPlatform - Azure platform type
type AzureBatchCEComputeConfigPlatform string

const (
	AzureBatchCEComputeConfigPlatformAzureBatch AzureBatchCEComputeConfigPlatform = "azure-batch"
)

func (e AzureBatchCEComputeConfigPlatform) ToPointer() *AzureBatchCEComputeConfigPlatform {
	return &e
}
func (e *AzureBatchCEComputeConfigPlatform) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "azure-batch":
		*e = AzureBatchCEComputeConfigPlatform(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AzureBatchCEComputeConfigPlatform: %v", v)
	}
}

type AzureBatchCEComputeConfigInput struct {
	// Azure credentials identifier
	CredentialsID string `json:"credentialsId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `json:"workspaceId,omitempty"`
	// Unique identifier for the compute environment
	ID *string `json:"id,omitempty"`
	// A unique name for this compute environment. Use only alphanumeric, dash, and underscore characters.
	Name string `json:"name"`
	// Optional description of the compute environment
	Description *string `json:"description,omitempty"`
	// Azure platform type
	Platform AzureBatchCEComputeConfigPlatform `json:"platform"`
	// Compute environment status
	Status *string `json:"status,omitempty"`
	// Timestamp when the compute environment was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the compute environment was last updated
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// Timestamp when the compute environment was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Flag indicating if the compute environment has been deleted
	Deleted *bool         `json:"deleted,omitempty"`
	Config  AzBatchConfig `json:"config"`
}

func (a AzureBatchCEComputeConfigInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureBatchCEComputeConfigInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureBatchCEComputeConfigInput) GetCredentialsID() string {
	if a == nil {
		return ""
	}
	return a.CredentialsID
}

func (a *AzureBatchCEComputeConfigInput) GetWorkspaceID() *int64 {
	if a == nil {
		return nil
	}
	return a.WorkspaceID
}

func (a *AzureBatchCEComputeConfigInput) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AzureBatchCEComputeConfigInput) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AzureBatchCEComputeConfigInput) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AzureBatchCEComputeConfigInput) GetPlatform() AzureBatchCEComputeConfigPlatform {
	if a == nil {
		return AzureBatchCEComputeConfigPlatform("")
	}
	return a.Platform
}

func (a *AzureBatchCEComputeConfigInput) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AzureBatchCEComputeConfigInput) GetDateCreated() *time.Time {
	if a == nil {
		return nil
	}
	return a.DateCreated
}

func (a *AzureBatchCEComputeConfigInput) GetLastUpdated() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUpdated
}

func (a *AzureBatchCEComputeConfigInput) GetLastUsed() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsed
}

func (a *AzureBatchCEComputeConfigInput) GetDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.Deleted
}

func (a *AzureBatchCEComputeConfigInput) GetConfig() AzBatchConfig {
	if a == nil {
		return AzBatchConfig{}
	}
	return a.Config
}

type AzureBatchCEComputeConfig struct {
	// Azure credentials identifier
	CredentialsID string `json:"credentialsId"`
	OrgID         *int64 `json:"orgId,omitempty"`
	// Workspace numeric identifier
	WorkspaceID *int64 `json:"workspaceId,omitempty"`
	// Unique identifier for the compute environment
	ID *string `json:"id,omitempty"`
	// A unique name for this compute environment. Use only alphanumeric, dash, and underscore characters.
	Name string `json:"name"`
	// Optional description of the compute environment
	Description *string `json:"description,omitempty"`
	// Azure platform type
	Platform AzureBatchCEComputeConfigPlatform `json:"platform"`
	// Compute environment status
	Status *string `json:"status,omitempty"`
	// Timestamp when the compute environment was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the compute environment was last updated
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// Timestamp when the compute environment was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Flag indicating if the compute environment has been deleted
	Deleted *bool         `json:"deleted,omitempty"`
	Config  AzBatchConfig `json:"config"`
}

func (a AzureBatchCEComputeConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureBatchCEComputeConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureBatchCEComputeConfig) GetCredentialsID() string {
	if a == nil {
		return ""
	}
	return a.CredentialsID
}

func (a *AzureBatchCEComputeConfig) GetOrgID() *int64 {
	if a == nil {
		return nil
	}
	return a.OrgID
}

func (a *AzureBatchCEComputeConfig) GetWorkspaceID() *int64 {
	if a == nil {
		return nil
	}
	return a.WorkspaceID
}

func (a *AzureBatchCEComputeConfig) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AzureBatchCEComputeConfig) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AzureBatchCEComputeConfig) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AzureBatchCEComputeConfig) GetPlatform() AzureBatchCEComputeConfigPlatform {
	if a == nil {
		return AzureBatchCEComputeConfigPlatform("")
	}
	return a.Platform
}

func (a *AzureBatchCEComputeConfig) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AzureBatchCEComputeConfig) GetDateCreated() *time.Time {
	if a == nil {
		return nil
	}
	return a.DateCreated
}

func (a *AzureBatchCEComputeConfig) GetLastUpdated() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUpdated
}

func (a *AzureBatchCEComputeConfig) GetLastUsed() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsed
}

func (a *AzureBatchCEComputeConfig) GetDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.Deleted
}

func (a *AzureBatchCEComputeConfig) GetConfig() AzBatchConfig {
	if a == nil {
		return AzBatchConfig{}
	}
	return a.Config
}
