// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// AzureEntraCredentialProviderType - Cloud provider type. Always set by the provider for this resource.
type AzureEntraCredentialProviderType string

const (
	AzureEntraCredentialProviderTypeAzureEntra AzureEntraCredentialProviderType = "azure_entra"
)

func (e AzureEntraCredentialProviderType) ToPointer() *AzureEntraCredentialProviderType {
	return &e
}
func (e *AzureEntraCredentialProviderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "azure_entra":
		*e = AzureEntraCredentialProviderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AzureEntraCredentialProviderType: %v", v)
	}
}

// AzureEntraCredentialDiscriminator - Authentication mode discriminator.
type AzureEntraCredentialDiscriminator string

const (
	AzureEntraCredentialDiscriminatorAzureEntra AzureEntraCredentialDiscriminator = "azure_entra"
)

func (e AzureEntraCredentialDiscriminator) ToPointer() *AzureEntraCredentialDiscriminator {
	return &e
}
func (e *AzureEntraCredentialDiscriminator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "azure_entra":
		*e = AzureEntraCredentialDiscriminator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AzureEntraCredentialDiscriminator: %v", v)
	}
}

type AzureEntraCredentialKeys struct {
	// Authentication mode discriminator.
	Discriminator *AzureEntraCredentialDiscriminator `default:"azure_entra" json:"discriminator"`
	// Azure Batch account name.
	BatchName string `json:"batchName"`
	// Azure Blob Storage account name.
	StorageName string `json:"storageName"`
	// Microsoft Entra tenant ID.
	TenantID string `json:"tenantId"`
	// Microsoft Entra service principal client (application) ID.
	ClientID string `json:"clientId"`
	// Microsoft Entra service principal client secret.
	ClientSecret string `json:"clientSecret"`
}

func (a AzureEntraCredentialKeys) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureEntraCredentialKeys) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureEntraCredentialKeys) GetDiscriminator() *AzureEntraCredentialDiscriminator {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureEntraCredentialKeys) GetBatchName() string {
	if a == nil {
		return ""
	}
	return a.BatchName
}

func (a *AzureEntraCredentialKeys) GetStorageName() string {
	if a == nil {
		return ""
	}
	return a.StorageName
}

func (a *AzureEntraCredentialKeys) GetTenantID() string {
	if a == nil {
		return ""
	}
	return a.TenantID
}

func (a *AzureEntraCredentialKeys) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *AzureEntraCredentialKeys) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}

type AzureEntraCredential struct {
	// Unique identifier for the credential (max 22 characters)
	CredentialsID *string `json:"id,omitempty"`
	// Display name for the credential. Must be 2-99 characters using only letters, numbers, underscores, and hyphens. No spaces allowed.
	Name string `json:"name"`
	// Cloud provider type. Always set by the provider for this resource.
	ProviderType *AzureEntraCredentialProviderType `default:"azure_entra" json:"provider"`
	// Flag indicating if the credential has been soft-deleted
	Deleted *bool `json:"deleted,omitempty"`
	// Timestamp when the credential was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Timestamp when the credential was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the credential was last updated
	LastUpdated *time.Time               `json:"lastUpdated,omitempty"`
	Keys        AzureEntraCredentialKeys `json:"keys"`
}

func (a AzureEntraCredential) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureEntraCredential) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureEntraCredential) GetCredentialsID() *string {
	if a == nil {
		return nil
	}
	return a.CredentialsID
}

func (a *AzureEntraCredential) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AzureEntraCredential) GetProviderType() *AzureEntraCredentialProviderType {
	if a == nil {
		return nil
	}
	return a.ProviderType
}

func (a *AzureEntraCredential) GetDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.Deleted
}

func (a *AzureEntraCredential) GetLastUsed() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsed
}

func (a *AzureEntraCredential) GetDateCreated() *time.Time {
	if a == nil {
		return nil
	}
	return a.DateCreated
}

func (a *AzureEntraCredential) GetLastUpdated() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUpdated
}

func (a *AzureEntraCredential) GetKeys() AzureEntraCredentialKeys {
	if a == nil {
		return AzureEntraCredentialKeys{}
	}
	return a.Keys
}

type AzureEntraCredentialKeysOutput struct {
	// Authentication mode discriminator.
	Discriminator *AzureEntraCredentialDiscriminator `default:"azure_entra" json:"discriminator"`
	// Azure Batch account name.
	BatchName string `json:"batchName"`
	// Azure Blob Storage account name.
	StorageName string `json:"storageName"`
	// Microsoft Entra tenant ID.
	TenantID string `json:"tenantId"`
	// Microsoft Entra service principal client (application) ID.
	ClientID string `json:"clientId"`
}

func (a AzureEntraCredentialKeysOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureEntraCredentialKeysOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureEntraCredentialKeysOutput) GetDiscriminator() *AzureEntraCredentialDiscriminator {
	if a == nil {
		return nil
	}
	return a.Discriminator
}

func (a *AzureEntraCredentialKeysOutput) GetBatchName() string {
	if a == nil {
		return ""
	}
	return a.BatchName
}

func (a *AzureEntraCredentialKeysOutput) GetStorageName() string {
	if a == nil {
		return ""
	}
	return a.StorageName
}

func (a *AzureEntraCredentialKeysOutput) GetTenantID() string {
	if a == nil {
		return ""
	}
	return a.TenantID
}

func (a *AzureEntraCredentialKeysOutput) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

type AzureEntraCredentialOutput struct {
	// Unique identifier for the credential (max 22 characters)
	CredentialsID *string `json:"id,omitempty"`
	// Display name for the credential. Must be 2-99 characters using only letters, numbers, underscores, and hyphens. No spaces allowed.
	Name string `json:"name"`
	// Cloud provider type. Always set by the provider for this resource.
	ProviderType *AzureEntraCredentialProviderType `default:"azure_entra" json:"provider"`
	// Flag indicating if the credential has been soft-deleted
	Deleted *bool `json:"deleted,omitempty"`
	// Timestamp when the credential was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Timestamp when the credential was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the credential was last updated
	LastUpdated *time.Time                     `json:"lastUpdated,omitempty"`
	Keys        AzureEntraCredentialKeysOutput `json:"keys"`
}

func (a AzureEntraCredentialOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureEntraCredentialOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AzureEntraCredentialOutput) GetCredentialsID() *string {
	if a == nil {
		return nil
	}
	return a.CredentialsID
}

func (a *AzureEntraCredentialOutput) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AzureEntraCredentialOutput) GetProviderType() *AzureEntraCredentialProviderType {
	if a == nil {
		return nil
	}
	return a.ProviderType
}

func (a *AzureEntraCredentialOutput) GetDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.Deleted
}

func (a *AzureEntraCredentialOutput) GetLastUsed() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUsed
}

func (a *AzureEntraCredentialOutput) GetDateCreated() *time.Time {
	if a == nil {
		return nil
	}
	return a.DateCreated
}

func (a *AzureEntraCredentialOutput) GetLastUpdated() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastUpdated
}

func (a *AzureEntraCredentialOutput) GetKeys() AzureEntraCredentialKeysOutput {
	if a == nil {
		return AzureEntraCredentialKeysOutput{}
	}
	return a.Keys
}
