// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Bucket struct {
	Path *string `json:"path,omitempty"`
}

func (o *Bucket) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}
