// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e1c918e85834

package shared

import (
	"encoding/json"
	"fmt"
)

type ComputeEnvQueryAttribute string

const (
	ComputeEnvQueryAttributeLabels    ComputeEnvQueryAttribute = "labels"
	ComputeEnvQueryAttributeResources ComputeEnvQueryAttribute = "resources"
)

func (e ComputeEnvQueryAttribute) ToPointer() *ComputeEnvQueryAttribute {
	return &e
}
func (e *ComputeEnvQueryAttribute) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "labels":
		fallthrough
	case "resources":
		*e = ComputeEnvQueryAttribute(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ComputeEnvQueryAttribute: %v", v)
	}
}
