// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAWSComputeEnvRequest struct {
	ComputeEnv *AWSComputeEnvComputeConfigInput `json:"computeEnv,omitempty"`
	LabelIds   []int64                          `json:"labelIds,omitempty"`
}

func (o *CreateAWSComputeEnvRequest) GetComputeEnv() *AWSComputeEnvComputeConfigInput {
	if o == nil {
		return nil
	}
	return o.ComputeEnv
}

func (o *CreateAWSComputeEnvRequest) GetLabelIds() []int64 {
	if o == nil {
		return nil
	}
	return o.LabelIds
}
