// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 283ba99a3085

package shared

type CreateOrganizationRequest struct {
	Organization *Organization `json:"organization,omitempty"`
}

func (c *CreateOrganizationRequest) GetOrganization() *Organization {
	if c == nil {
		return nil
	}
	return c.Organization
}
