// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ea8b59d759e1

package shared

type CreateSSHKeyResponse struct {
	SSHKey *UserSSHPublicKeyDto `json:"sshKey,omitempty"`
}

func (c *CreateSSHKeyResponse) GetSSHKey() *UserSSHPublicKeyDto {
	if c == nil {
		return nil
	}
	return c.SSHKey
}
