// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateDatasetRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

func (c *CreateDatasetRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateDatasetRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}
