// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateOrganizationResponse struct {
	Organization *OrganizationDbDto `json:"organization,omitempty"`
}

func (o *CreateOrganizationResponse) GetOrganization() *OrganizationDbDto {
	if o == nil {
		return nil
	}
	return o.Organization
}
