// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAzureBatchCERequest struct {
	ComputeEnv *AzureBatchCEComputeConfigInput `json:"computeEnv,omitempty"`
	LabelIds   []int64                         `json:"labelIds,omitempty"`
}

func (c *CreateAzureBatchCERequest) GetComputeEnv() *AzureBatchCEComputeConfigInput {
	if c == nil {
		return nil
	}
	return c.ComputeEnv
}

func (c *CreateAzureBatchCERequest) GetLabelIds() []int64 {
	if c == nil {
		return nil
	}
	return c.LabelIds
}
