// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAWSComputeEnvResponse struct {
	ComputeEnvID *string `json:"computeEnvId,omitempty"`
}

func (c *CreateAWSComputeEnvResponse) GetComputeEnvID() *string {
	if c == nil {
		return nil
	}
	return c.ComputeEnvID
}
