// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateTeamMemberRequest struct {
	UserNameOrEmail *string `json:"userNameOrEmail,omitempty"`
}

func (c *CreateTeamMemberRequest) GetUserNameOrEmail() *string {
	if c == nil {
		return nil
	}
	return c.UserNameOrEmail
}
