// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAWSComputeEnvResponse struct {
	ComputeEnvID *string `json:"computeEnvId,omitempty"`
}

func (o *CreateAWSComputeEnvResponse) GetComputeEnvID() *string {
	if o == nil {
		return nil
	}
	return o.ComputeEnvID
}
