// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateKubernetesCredentialsRequest struct {
	Credentials *KubernetesCredential `json:"credentials,omitempty"`
}

func (c *CreateKubernetesCredentialsRequest) GetCredentials() *KubernetesCredential {
	if c == nil {
		return nil
	}
	return c.Credentials
}
