// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAWSCredentialsResponse struct {
	CredentialsID *string `json:"credentialsId,omitempty"`
}

func (c *CreateAWSCredentialsResponse) GetCredentialsID() *string {
	if c == nil {
		return nil
	}
	return c.CredentialsID
}
