// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateOrganizationRequest struct {
	Organization *Organization `json:"organization,omitempty"`
	LogoID       *string       `json:"logoId,omitempty"`
}

func (c *CreateOrganizationRequest) GetOrganization() *Organization {
	if c == nil {
		return nil
	}
	return c.Organization
}

func (c *CreateOrganizationRequest) GetLogoID() *string {
	if c == nil {
		return nil
	}
	return c.LogoID
}
