// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateWorkspaceResponse struct {
	Workspace *Workspace `json:"workspace,omitempty"`
}

func (o *CreateWorkspaceResponse) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}
	return o.Workspace
}
