// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateCodeCommitCredentialsRequest struct {
	Credentials *CodeCommitCredential `json:"credentials,omitempty"`
}

func (c *CreateCodeCommitCredentialsRequest) GetCredentials() *CodeCommitCredential {
	if c == nil {
		return nil
	}
	return c.Credentials
}
