// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAccessTokenResponse struct {
	AccessKey *string `json:"accessKey,omitempty"`
	// Represents an API access token for authentication.
	// Contains token metadata, permissions, and expiration information
	// for secure API access to platform resources.
	//
	Token *AccessToken `json:"token,omitempty"`
}

func (c *CreateAccessTokenResponse) GetAccessKey() *string {
	if c == nil {
		return nil
	}
	return c.AccessKey
}

func (c *CreateAccessTokenResponse) GetToken() *AccessToken {
	if c == nil {
		return nil
	}
	return c.Token
}
