// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateDatasetResponse struct {
	// Represents a dataset in the Seqera Platform.
	// Contains dataset metadata, versioning information, and access
	// controls for data management and sharing.
	//
	Dataset *DatasetDto `json:"dataset,omitempty"`
}

func (c *CreateDatasetResponse) GetDataset() *DatasetDto {
	if c == nil {
		return nil
	}
	return c.Dataset
}
