// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateAWSBatchComputeEnvRequest struct {
	ComputeEnv *AWSBatchComputeEnv `json:"computeEnv,omitempty"`
	LabelIds   []int64             `json:"labelIds,omitempty"`
}

func (c *CreateAWSBatchComputeEnvRequest) GetComputeEnv() *AWSBatchComputeEnv {
	if c == nil {
		return nil
	}
	return c.ComputeEnv
}

func (c *CreateAWSBatchComputeEnvRequest) GetLabelIds() []int64 {
	if c == nil {
		return nil
	}
	return c.LabelIds
}
