// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type DataStudioCheckpointDto struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	DateCreated time.Time  `json:"dateCreated"`
	DateSaved   time.Time  `json:"dateSaved"`
	Author      StudioUser `json:"author"`
	Path        string     `json:"path"`
}

func (d DataStudioCheckpointDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DataStudioCheckpointDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id", "name", "dateCreated", "dateSaved", "author", "path"}); err != nil {
		return err
	}
	return nil
}

func (d *DataStudioCheckpointDto) GetID() int64 {
	if d == nil {
		return 0
	}
	return d.ID
}

func (d *DataStudioCheckpointDto) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DataStudioCheckpointDto) GetDateCreated() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.DateCreated
}

func (d *DataStudioCheckpointDto) GetDateSaved() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.DateSaved
}

func (d *DataStudioCheckpointDto) GetAuthor() StudioUser {
	if d == nil {
		return StudioUser{}
	}
	return d.Author
}

func (d *DataStudioCheckpointDto) GetPath() string {
	if d == nil {
		return ""
	}
	return d.Path
}
