// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type DatasetImage struct {
	AuditImageType  AuditImageType `json:"auditImageType"`
	Description     *string        `json:"description,omitempty"`
	Hidden          *bool          `json:"hidden,omitempty"`
	LastUpdatedByID *int64         `json:"lastUpdatedById,omitempty"`
	MediaType       *string        `json:"mediaType,omitempty"`
	Name            *string        `json:"name,omitempty"`
	SourceType      *string        `json:"sourceType,omitempty"`
}

func (d DatasetImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatasetImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DatasetImage) GetAuditImageType() AuditImageType {
	if d == nil {
		return AuditImageType("")
	}
	return d.AuditImageType
}

func (d *DatasetImage) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DatasetImage) GetHidden() *bool {
	if d == nil {
		return nil
	}
	return d.Hidden
}

func (d *DatasetImage) GetLastUpdatedByID() *int64 {
	if d == nil {
		return nil
	}
	return d.LastUpdatedByID
}

func (d *DatasetImage) GetMediaType() *string {
	if d == nil {
		return nil
	}
	return d.MediaType
}

func (d *DatasetImage) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DatasetImage) GetSourceType() *string {
	if d == nil {
		return nil
	}
	return d.SourceType
}
