// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type DataLinkMetadataImage struct {
	AuditImageType AuditImageType `json:"auditImageType"`
	Hidden         *bool          `json:"hidden,omitempty"`
}

func (d DataLinkMetadataImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DataLinkMetadataImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DataLinkMetadataImage) GetAuditImageType() AuditImageType {
	if d == nil {
		return AuditImageType("")
	}
	return d.AuditImageType
}

func (d *DataLinkMetadataImage) GetHidden() *bool {
	if d == nil {
		return nil
	}
	return d.Hidden
}
