// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Configuration struct {
	Gpu              *int              `json:"gpu,omitempty"`
	CPU              *int              `json:"cpu,omitempty"`
	Memory           *int              `json:"memory,omitempty"`
	MountData        []string          `json:"mountData,omitempty"`
	Environment      map[string]string `json:"environment,omitempty"`
	CondaEnvironment *string           `json:"condaEnvironment,omitempty"`
	LifespanHours    *int              `json:"lifespanHours,omitempty"`
}

func (o *Configuration) GetGpu() *int {
	if o == nil {
		return nil
	}
	return o.Gpu
}

func (o *Configuration) GetCPU() *int {
	if o == nil {
		return nil
	}
	return o.CPU
}

func (o *Configuration) GetMemory() *int {
	if o == nil {
		return nil
	}
	return o.Memory
}

func (o *Configuration) GetMountData() []string {
	if o == nil {
		return nil
	}
	return o.MountData
}

func (o *Configuration) GetEnvironment() map[string]string {
	if o == nil {
		return nil
	}
	return o.Environment
}

func (o *Configuration) GetCondaEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.CondaEnvironment
}

func (o *Configuration) GetLifespanHours() *int {
	if o == nil {
		return nil
	}
	return o.LifespanHours
}

type DataStudioStartRequest struct {
	Configuration *Configuration `json:"configuration,omitempty"`
	Description   *string        `json:"description,omitempty"`
	LabelIds      []int64        `json:"labelIds,omitempty"`
	Spot          *bool          `json:"spot,omitempty"`
}

func (o *DataStudioStartRequest) GetConfiguration() *Configuration {
	if o == nil {
		return nil
	}
	return o.Configuration
}

func (o *DataStudioStartRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *DataStudioStartRequest) GetLabelIds() []int64 {
	if o == nil {
		return nil
	}
	return o.LabelIds
}

func (o *DataStudioStartRequest) GetSpot() *bool {
	if o == nil {
		return nil
	}
	return o.Spot
}
