// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataLinkContentTreeListResponse struct {
	Items []DataLinkSimpleItem `json:"items"`
}

func (d *DataLinkContentTreeListResponse) GetItems() []DataLinkSimpleItem {
	if d == nil {
		return []DataLinkSimpleItem{}
	}
	return d.Items
}
