// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataStudioCreateRequest struct {
	Name                string                  `json:"name"`
	Description         *string                 `json:"description,omitempty"`
	DataStudioToolURL   string                  `json:"dataStudioToolUrl"`
	ComputeEnvID        string                  `json:"computeEnvId"`
	InitialCheckpointID *int64                  `json:"initialCheckpointId,omitempty"`
	Configuration       DataStudioConfiguration `json:"configuration"`
	IsPrivate           *bool                   `json:"isPrivate,omitempty"`
	// List of resource label IDs to associate with this Studio. Reference labels using seqera_labels.label_name.id
	LabelIds []int64 `json:"labelIds,omitempty"`
	// Whether to use spot or on-demand instances. Studios using Spot instances are not compatible with batch compute environments.
	Spot *bool `json:"spot,omitempty"`
}

func (d *DataStudioCreateRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DataStudioCreateRequest) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DataStudioCreateRequest) GetDataStudioToolURL() string {
	if d == nil {
		return ""
	}
	return d.DataStudioToolURL
}

func (d *DataStudioCreateRequest) GetComputeEnvID() string {
	if d == nil {
		return ""
	}
	return d.ComputeEnvID
}

func (d *DataStudioCreateRequest) GetInitialCheckpointID() *int64 {
	if d == nil {
		return nil
	}
	return d.InitialCheckpointID
}

func (d *DataStudioCreateRequest) GetConfiguration() DataStudioConfiguration {
	if d == nil {
		return DataStudioConfiguration{}
	}
	return d.Configuration
}

func (d *DataStudioCreateRequest) GetIsPrivate() *bool {
	if d == nil {
		return nil
	}
	return d.IsPrivate
}

func (d *DataStudioCreateRequest) GetLabelIds() []int64 {
	if d == nil {
		return nil
	}
	return d.LabelIds
}

func (d *DataStudioCreateRequest) GetSpot() *bool {
	if d == nil {
		return nil
	}
	return d.Spot
}
