// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Configuration struct {
	// Number of GPUs to allocate
	Gpu *int `json:"gpu,omitempty"`
	// Number of CPU cores to allocate
	CPU *int `json:"cpu,omitempty"`
	// Memory allocation for the Studio session in megabytes (MB).
	Memory           *int     `json:"memory,omitempty"`
	MountData        []string `json:"mountData,omitempty"`
	CondaEnvironment *string  `json:"condaEnvironment,omitempty"`
	// Maximum lifespan of the Studio session in hours
	LifespanHours *int `json:"lifespanHours,omitempty"`
}

func (c *Configuration) GetGpu() *int {
	if c == nil {
		return nil
	}
	return c.Gpu
}

func (c *Configuration) GetCPU() *int {
	if c == nil {
		return nil
	}
	return c.CPU
}

func (c *Configuration) GetMemory() *int {
	if c == nil {
		return nil
	}
	return c.Memory
}

func (c *Configuration) GetMountData() []string {
	if c == nil {
		return nil
	}
	return c.MountData
}

func (c *Configuration) GetCondaEnvironment() *string {
	if c == nil {
		return nil
	}
	return c.CondaEnvironment
}

func (c *Configuration) GetLifespanHours() *int {
	if c == nil {
		return nil
	}
	return c.LifespanHours
}

type DataStudioStartRequest struct {
	Configuration *Configuration `json:"configuration,omitempty"`
	Description   *string        `json:"description,omitempty"`
	LabelIds      []int64        `json:"labelIds,omitempty"`
	Spot          *bool          `json:"spot,omitempty"`
}

func (d *DataStudioStartRequest) GetConfiguration() *Configuration {
	if d == nil {
		return nil
	}
	return d.Configuration
}

func (d *DataStudioStartRequest) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DataStudioStartRequest) GetLabelIds() []int64 {
	if d == nil {
		return nil
	}
	return d.LabelIds
}

func (d *DataStudioStartRequest) GetSpot() *bool {
	if d == nil {
		return nil
	}
	return d.Spot
}
