// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataStudioConfiguration struct {
	// Number of GPUs to allocate
	Gpu *int `json:"gpu,omitempty"`
	// Number of CPU cores to allocate
	CPU *int `json:"cpu,omitempty"`
	// Memory allocation for the Studio session in megabytes (MB).
	Memory           *int     `json:"memory,omitempty"`
	MountData        []string `json:"mountData,omitempty"`
	CondaEnvironment *string  `json:"condaEnvironment,omitempty"`
	// Maximum lifespan of the Studio session in hours
	LifespanHours *int `json:"lifespanHours,omitempty"`
}

func (d *DataStudioConfiguration) GetGpu() *int {
	if d == nil {
		return nil
	}
	return d.Gpu
}

func (d *DataStudioConfiguration) GetCPU() *int {
	if d == nil {
		return nil
	}
	return d.CPU
}

func (d *DataStudioConfiguration) GetMemory() *int {
	if d == nil {
		return nil
	}
	return d.Memory
}

func (d *DataStudioConfiguration) GetMountData() []string {
	if d == nil {
		return nil
	}
	return d.MountData
}

func (d *DataStudioConfiguration) GetCondaEnvironment() *string {
	if d == nil {
		return nil
	}
	return d.CondaEnvironment
}

func (d *DataStudioConfiguration) GetLifespanHours() *int {
	if d == nil {
		return nil
	}
	return d.LifespanHours
}
