// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataLinkDownloadURLResponse struct {
	URL *string `json:"url,omitempty"`
}

func (o *DataLinkDownloadURLResponse) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
