// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DataStudioProgressStep struct {
	Status   *DataStudioProgressStepStatus `json:"status,omitempty"`
	Message  *string                       `json:"message,omitempty"`
	Warnings []string                      `json:"warnings,omitempty"`
}

func (d *DataStudioProgressStep) GetStatus() *DataStudioProgressStepStatus {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DataStudioProgressStep) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DataStudioProgressStep) GetWarnings() []string {
	if d == nil {
		return nil
	}
	return d.Warnings
}
