// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeGitlabCredentialsResponse struct {
	Credentials *GitlabCredentialOutput `json:"credentials,omitempty"`
}

func (d *DescribeGitlabCredentialsResponse) GetCredentials() *GitlabCredentialOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}
