// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5b7149929e4d

package shared

type DescribeWorkspaceResponse struct {
	Workspace *Workspace `json:"workspace,omitempty"`
}

func (d *DescribeWorkspaceResponse) GetWorkspace() *Workspace {
	if d == nil {
		return nil
	}
	return d.Workspace
}
