// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeActionResponse struct {
	// Represents a pipeline action in the Seqera Platform.
	// Contains action configuration, triggers, and execution settings
	// for automated pipeline workflows.
	//
	Action *ActionResponseDto `json:"action,omitempty"`
}

func (o *DescribeActionResponse) GetAction() *ActionResponseDto {
	if o == nil {
		return nil
	}
	return o.Action
}
