// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeCredentialsResponse struct {
	// Represents credentials used for authentication with various platforms and services.
	// Contains authentication information for accessing cloud providers, Git repositories,
	// and other external services within the Seqera Platform.
	//
	Credentials *CredentialsOutput `json:"credentials,omitempty"`
	// Server-rendered, read-only provider-side setup snippet (e.g. AWS IAM role trust policy) to paste at the cloud provider. Populated when a renderer is available for the credential type and the installation is configured for it; otherwise omitted.
	SetupSnippet *string `json:"setupSnippet,omitempty"`
	// Read-only labelled values the administrator copies into their cloud provider console to finish setting up the credential. Empty when nothing applies to the credential type.
	SetupValues []CredentialsSetupValue `json:"setupValues,omitempty"`
}

func (d *DescribeCredentialsResponse) GetCredentials() *CredentialsOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}

func (d *DescribeCredentialsResponse) GetSetupSnippet() *string {
	if d == nil {
		return nil
	}
	return d.SetupSnippet
}

func (d *DescribeCredentialsResponse) GetSetupValues() []CredentialsSetupValue {
	if d == nil {
		return nil
	}
	return d.SetupValues
}
