// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeSSHCredentialsResponse struct {
	Credentials *SSHCredentialOutput `json:"credentials,omitempty"`
}

func (d *DescribeSSHCredentialsResponse) GetCredentials() *SSHCredentialOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}
