// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeCredentialsResponse struct {
	Credentials *CredentialsOutput `json:"credentials,omitempty"`
}

func (o *DescribeCredentialsResponse) GetCredentials() *CredentialsOutput {
	if o == nil {
		return nil
	}
	return o.Credentials
}
