// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeAWSCredentialsResponse struct {
	Credentials *AWSCredentialOutput `json:"credentials,omitempty"`
}

func (d *DescribeAWSCredentialsResponse) GetCredentials() *AWSCredentialOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}
