// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeContainerRegistryCredentialsResponse struct {
	Credentials *ContainerRegistryCredentialOutput `json:"credentials,omitempty"`
}

func (d *DescribeContainerRegistryCredentialsResponse) GetCredentials() *ContainerRegistryCredentialOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}
