// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeCodeCommitCredentialsResponse struct {
	Credentials *CodeCommitCredentialOutput `json:"credentials,omitempty"`
}

func (d *DescribeCodeCommitCredentialsResponse) GetCredentials() *CodeCommitCredentialOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}
