// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribePlatformResponse struct {
	Metainfo *PlatformMetainfo `json:"metainfo,omitempty"`
}

func (d *DescribePlatformResponse) GetMetainfo() *PlatformMetainfo {
	if d == nil {
		return nil
	}
	return d.Metainfo
}

func (d *DescribePlatformResponse) GetMetainfoGkePlatform() *GkePlatformMetaInfo {
	if v := d.GetMetainfo(); v != nil {
		return v.GkePlatformMetaInfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoAwsCloud() *AwsCloudPlatformMetainfo {
	if v := d.GetMetainfo(); v != nil {
		return v.AwsCloudPlatformMetainfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoK8sPlatform() *K8sPlatformMetaInfo {
	if v := d.GetMetainfo(); v != nil {
		return v.K8sPlatformMetaInfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoGrid() *GridPlatformMetainfo {
	if v := d.GetMetainfo(); v != nil {
		return v.GridPlatformMetainfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoAwsBatch() *AwsBatchPlatformMetainfo {
	if v := d.GetMetainfo(); v != nil {
		return v.AwsBatchPlatformMetainfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoLocalPlatform() *LocalPlatformMetainfo {
	if v := d.GetMetainfo(); v != nil {
		return v.LocalPlatformMetainfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoGoogle() *GooglePlatformMetainfo {
	if v := d.GetMetainfo(); v != nil {
		return v.GooglePlatformMetainfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoAzureBatch() *AzBatchPlatformMetainfo {
	if v := d.GetMetainfo(); v != nil {
		return v.AzBatchPlatformMetainfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoEksPlatform() *EksPlatformMetaInfo {
	if v := d.GetMetainfo(); v != nil {
		return v.EksPlatformMetaInfo
	}
	return nil
}

func (d *DescribePlatformResponse) GetMetainfoAzureCloud() *AzCloudPlatformMetaInfo {
	if v := d.GetMetainfo(); v != nil {
		return v.AzCloudPlatformMetaInfo
	}
	return nil
}
