// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DescribeTeamResponse struct {
	// Represents a team within an organization.
	// Contains team membership, permissions, and access controls
	// for collaborative workspace management.
	Team *TeamDbDto `json:"team,omitempty"`
}

func (o *DescribeTeamResponse) GetTeam() *TeamDbDto {
	if o == nil {
		return nil
	}
	return o.Team
}
