// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 08f4e831ace6

package shared

type DescribeTowerAgentCredentialsResponse struct {
	Credentials *TowerAgentCredentialOutput `json:"credentials,omitempty"`
}

func (d *DescribeTowerAgentCredentialsResponse) GetCredentials() *TowerAgentCredentialOutput {
	if d == nil {
		return nil
	}
	return d.Credentials
}
