// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type GithubActionEvent struct {
	ActionEventType string     `json:"actionEventType"`
	Timestamp       *time.Time `json:"timestamp,omitempty"`
	Ref             *string    `json:"ref,omitempty"`
	CommitID        *string    `json:"commitId,omitempty"`
	CommitMessage   *string    `json:"commitMessage,omitempty"`
	PusherName      *string    `json:"pusherName,omitempty"`
	PusherEmail     *string    `json:"pusherEmail,omitempty"`
}

func (g GithubActionEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GithubActionEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GithubActionEvent) GetActionEventType() string {
	if g == nil {
		return ""
	}
	return g.ActionEventType
}

func (g *GithubActionEvent) GetTimestamp() *time.Time {
	if g == nil {
		return nil
	}
	return g.Timestamp
}

func (g *GithubActionEvent) GetRef() *string {
	if g == nil {
		return nil
	}
	return g.Ref
}

func (g *GithubActionEvent) GetCommitID() *string {
	if g == nil {
		return nil
	}
	return g.CommitID
}

func (g *GithubActionEvent) GetCommitMessage() *string {
	if g == nil {
		return nil
	}
	return g.CommitMessage
}

func (g *GithubActionEvent) GetPusherName() *string {
	if g == nil {
		return nil
	}
	return g.PusherName
}

func (g *GithubActionEvent) GetPusherEmail() *string {
	if g == nil {
		return nil
	}
	return g.PusherEmail
}
