// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// GoogleBatchCEComputeConfigPlatform - Google Cloud platform type (defaults to google-batch)
type GoogleBatchCEComputeConfigPlatform string

const (
	GoogleBatchCEComputeConfigPlatformGoogleBatch GoogleBatchCEComputeConfigPlatform = "google-batch"
)

func (e GoogleBatchCEComputeConfigPlatform) ToPointer() *GoogleBatchCEComputeConfigPlatform {
	return &e
}
func (e *GoogleBatchCEComputeConfigPlatform) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "google-batch":
		*e = GoogleBatchCEComputeConfigPlatform(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GoogleBatchCEComputeConfigPlatform: %v", v)
	}
}

type GoogleBatchCEComputeConfigInput struct {
	// Google Cloud credentials identifier
	CredentialsID string `json:"credentialsId"`
	// Workspace numeric identifier
	WorkspaceID *int64 `json:"workspaceId,omitempty"`
	// Unique identifier for the compute environment
	ID *string `json:"id,omitempty"`
	// A unique name for this compute environment. Use only alphanumeric, dash, and underscore characters.
	Name string `json:"name"`
	// Optional description of the compute environment
	Description *string `json:"description,omitempty"`
	// Google Cloud platform type (defaults to google-batch)
	Platform *GoogleBatchCEComputeConfigPlatform `default:"google-batch" json:"platform"`
	// Compute environment status
	Status *string `json:"status,omitempty"`
	// Timestamp when the compute environment was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the compute environment was last updated
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// Timestamp when the compute environment was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Flag indicating if the compute environment has been deleted
	Deleted *bool             `json:"deleted,omitempty"`
	Config  GoogleBatchConfig `json:"config"`
}

func (g GoogleBatchCEComputeConfigInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GoogleBatchCEComputeConfigInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GoogleBatchCEComputeConfigInput) GetCredentialsID() string {
	if g == nil {
		return ""
	}
	return g.CredentialsID
}

func (g *GoogleBatchCEComputeConfigInput) GetWorkspaceID() *int64 {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

func (g *GoogleBatchCEComputeConfigInput) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GoogleBatchCEComputeConfigInput) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GoogleBatchCEComputeConfigInput) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GoogleBatchCEComputeConfigInput) GetPlatform() *GoogleBatchCEComputeConfigPlatform {
	if g == nil {
		return nil
	}
	return g.Platform
}

func (g *GoogleBatchCEComputeConfigInput) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GoogleBatchCEComputeConfigInput) GetDateCreated() *time.Time {
	if g == nil {
		return nil
	}
	return g.DateCreated
}

func (g *GoogleBatchCEComputeConfigInput) GetLastUpdated() *time.Time {
	if g == nil {
		return nil
	}
	return g.LastUpdated
}

func (g *GoogleBatchCEComputeConfigInput) GetLastUsed() *time.Time {
	if g == nil {
		return nil
	}
	return g.LastUsed
}

func (g *GoogleBatchCEComputeConfigInput) GetDeleted() *bool {
	if g == nil {
		return nil
	}
	return g.Deleted
}

func (g *GoogleBatchCEComputeConfigInput) GetConfig() GoogleBatchConfig {
	if g == nil {
		return GoogleBatchConfig{}
	}
	return g.Config
}

type GoogleBatchCEComputeConfig struct {
	// Google Cloud credentials identifier
	CredentialsID string `json:"credentialsId"`
	OrgID         *int64 `json:"orgId,omitempty"`
	// Workspace numeric identifier
	WorkspaceID *int64 `json:"workspaceId,omitempty"`
	// Unique identifier for the compute environment
	ID *string `json:"id,omitempty"`
	// A unique name for this compute environment. Use only alphanumeric, dash, and underscore characters.
	Name string `json:"name"`
	// Optional description of the compute environment
	Description *string `json:"description,omitempty"`
	// Google Cloud platform type (defaults to google-batch)
	Platform *GoogleBatchCEComputeConfigPlatform `default:"google-batch" json:"platform"`
	// Compute environment status
	Status *string `json:"status,omitempty"`
	// Timestamp when the compute environment was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Timestamp when the compute environment was last updated
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	// Timestamp when the compute environment was last used
	LastUsed *time.Time `json:"lastUsed,omitempty"`
	// Flag indicating if the compute environment has been deleted
	Deleted *bool             `json:"deleted,omitempty"`
	Config  GoogleBatchConfig `json:"config"`
}

func (g GoogleBatchCEComputeConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GoogleBatchCEComputeConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GoogleBatchCEComputeConfig) GetCredentialsID() string {
	if g == nil {
		return ""
	}
	return g.CredentialsID
}

func (g *GoogleBatchCEComputeConfig) GetOrgID() *int64 {
	if g == nil {
		return nil
	}
	return g.OrgID
}

func (g *GoogleBatchCEComputeConfig) GetWorkspaceID() *int64 {
	if g == nil {
		return nil
	}
	return g.WorkspaceID
}

func (g *GoogleBatchCEComputeConfig) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GoogleBatchCEComputeConfig) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GoogleBatchCEComputeConfig) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GoogleBatchCEComputeConfig) GetPlatform() *GoogleBatchCEComputeConfigPlatform {
	if g == nil {
		return nil
	}
	return g.Platform
}

func (g *GoogleBatchCEComputeConfig) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GoogleBatchCEComputeConfig) GetDateCreated() *time.Time {
	if g == nil {
		return nil
	}
	return g.DateCreated
}

func (g *GoogleBatchCEComputeConfig) GetLastUpdated() *time.Time {
	if g == nil {
		return nil
	}
	return g.LastUpdated
}

func (g *GoogleBatchCEComputeConfig) GetLastUsed() *time.Time {
	if g == nil {
		return nil
	}
	return g.LastUsed
}

func (g *GoogleBatchCEComputeConfig) GetDeleted() *bool {
	if g == nil {
		return nil
	}
	return g.Deleted
}

func (g *GoogleBatchCEComputeConfig) GetConfig() GoogleBatchConfig {
	if g == nil {
		return GoogleBatchConfig{}
	}
	return g.Config
}
