// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type GoogleSecurityKeys struct {
	CredentialType string  `json:"credentialType"`
	Discriminator  *string `json:"discriminator,omitempty"`
	Data           *string `json:"data,omitempty"`
}

func (g GoogleSecurityKeys) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GoogleSecurityKeys) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GoogleSecurityKeys) GetCredentialType() string {
	if g == nil {
		return ""
	}
	return g.CredentialType
}

func (g *GoogleSecurityKeys) GetDiscriminator() *string {
	if g == nil {
		return nil
	}
	return g.Discriminator
}

func (g *GoogleSecurityKeys) GetData() *string {
	if g == nil {
		return nil
	}
	return g.Data
}
