// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListManagedCredentialsResponse struct {
	ManagedCredentials []ListManagedCredentialsRespDto `json:"managedCredentials,omitempty"`
	TotalSize          *int64                          `json:"totalSize,omitempty"`
}

func (l *ListManagedCredentialsResponse) GetManagedCredentials() []ListManagedCredentialsRespDto {
	if l == nil {
		return nil
	}
	return l.ManagedCredentials
}

func (l *ListManagedCredentialsResponse) GetTotalSize() *int64 {
	if l == nil {
		return nil
	}
	return l.TotalSize
}
