// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListTeamResponse struct {
	Teams     []TeamDbDto `json:"teams,omitempty"`
	TotalSize *int64      `json:"totalSize,omitempty"`
}

func (l *ListTeamResponse) GetTeams() []TeamDbDto {
	if l == nil {
		return nil
	}
	return l.Teams
}

func (l *ListTeamResponse) GetTotalSize() *int64 {
	if l == nil {
		return nil
	}
	return l.TotalSize
}
