// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type ListActionsResponseActionInfo struct {
	Config      *ActionConfigType `json:"config,omitempty"`
	DateCreated *time.Time        `json:"dateCreated,omitempty"`
	Endpoint    *string           `json:"endpoint,omitempty"`
	Error       *string           `json:"error,omitempty"`
	Event       *ActionEventType  `json:"event,omitempty"`
	Hint        *string           `json:"hint,omitempty"`
	ID          *string           `json:"id,omitempty"`
	Labels      []LabelDbDto      `json:"labels,omitempty"`
	// Last seen timestamp (null if never seen)
	LastSeen      *time.Time `json:"lastSeen,omitempty"`
	Name          *string    `json:"name,omitempty"`
	NextExecution *time.Time `json:"nextExecution,omitempty"`
	// Pipeline name
	Pipeline *string       `json:"pipeline,omitempty"`
	Source   *ActionSource `json:"source,omitempty"`
	Status   *ActionStatus `json:"status,omitempty"`
	UsageCmd *string       `json:"usageCmd,omitempty"`
}

func (l ListActionsResponseActionInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListActionsResponseActionInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetConfig() *ActionConfigType {
	if l == nil {
		return nil
	}
	return l.Config
}

func (l *ListActionsResponseActionInfo) GetConfigBucket() *BucketActionConfig {
	if v := l.GetConfig(); v != nil {
		return v.BucketActionConfig
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetConfigCron() *CronActionConfig {
	if v := l.GetConfig(); v != nil {
		return v.CronActionConfig
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetConfigGithub() *GithubActionConfig {
	if v := l.GetConfig(); v != nil {
		return v.GithubActionConfig
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetConfigTower() *ActionTowerActionConfig {
	if v := l.GetConfig(); v != nil {
		return v.ActionTowerActionConfig
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetDateCreated() *time.Time {
	if l == nil {
		return nil
	}
	return l.DateCreated
}

func (l *ListActionsResponseActionInfo) GetEndpoint() *string {
	if l == nil {
		return nil
	}
	return l.Endpoint
}

func (l *ListActionsResponseActionInfo) GetError() *string {
	if l == nil {
		return nil
	}
	return l.Error
}

func (l *ListActionsResponseActionInfo) GetEvent() *ActionEventType {
	if l == nil {
		return nil
	}
	return l.Event
}

func (l *ListActionsResponseActionInfo) GetEventBucket() *BucketActionEvent {
	if v := l.GetEvent(); v != nil {
		return v.BucketActionEvent
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetEventCron() *CronActionEvent {
	if v := l.GetEvent(); v != nil {
		return v.CronActionEvent
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetEventGithub() *GithubActionEvent {
	if v := l.GetEvent(); v != nil {
		return v.GithubActionEvent
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetEventTower() *ActionTowerActionEvent {
	if v := l.GetEvent(); v != nil {
		return v.ActionTowerActionEvent
	}
	return nil
}

func (l *ListActionsResponseActionInfo) GetHint() *string {
	if l == nil {
		return nil
	}
	return l.Hint
}

func (l *ListActionsResponseActionInfo) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *ListActionsResponseActionInfo) GetLabels() []LabelDbDto {
	if l == nil {
		return nil
	}
	return l.Labels
}

func (l *ListActionsResponseActionInfo) GetLastSeen() *time.Time {
	if l == nil {
		return nil
	}
	return l.LastSeen
}

func (l *ListActionsResponseActionInfo) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListActionsResponseActionInfo) GetNextExecution() *time.Time {
	if l == nil {
		return nil
	}
	return l.NextExecution
}

func (l *ListActionsResponseActionInfo) GetPipeline() *string {
	if l == nil {
		return nil
	}
	return l.Pipeline
}

func (l *ListActionsResponseActionInfo) GetSource() *ActionSource {
	if l == nil {
		return nil
	}
	return l.Source
}

func (l *ListActionsResponseActionInfo) GetStatus() *ActionStatus {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListActionsResponseActionInfo) GetUsageCmd() *string {
	if l == nil {
		return nil
	}
	return l.UsageCmd
}
