// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f4510616e78a

package shared

type ListPlatformsResponse struct {
	Platforms []ComputePlatform `json:"platforms,omitempty"`
}

func (l *ListPlatformsResponse) GetPlatforms() []ComputePlatform {
	if l == nil {
		return nil
	}
	return l.Platforms
}
