// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListWorkflowsResponse struct {
	Workflows []ListWorkflowsResponseListWorkflowsElement `json:"workflows,omitempty"`
	TotalSize *int64                                      `json:"totalSize,omitempty"`
}

func (o *ListWorkflowsResponse) GetWorkflows() []ListWorkflowsResponseListWorkflowsElement {
	if o == nil {
		return nil
	}
	return o.Workflows
}

func (o *ListWorkflowsResponse) GetTotalSize() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalSize
}
