// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListComputeEnvsResponse struct {
	ComputeEnvs []ListComputeEnvsResponseEntry `json:"computeEnvs,omitempty"`
}

func (l *ListComputeEnvsResponse) GetComputeEnvs() []ListComputeEnvsResponseEntry {
	if l == nil {
		return nil
	}
	return l.ComputeEnvs
}
