// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListPipelineInfoResponse struct {
	Pipelines []string `json:"pipelines,omitempty"`
}

func (l *ListPipelineInfoResponse) GetPipelines() []string {
	if l == nil {
		return nil
	}
	return l.Pipelines
}
