// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NavbarConfig struct {
	Menus []NavbarConfigNavbarMenu `json:"menus,omitempty"`
}

func (o *NavbarConfig) GetMenus() []NavbarConfigNavbarMenu {
	if o == nil {
		return nil
	}
	return o.Menus
}
