// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ResolveCronExpressionRequest struct {
	Text string `json:"text"`
}

func (r *ResolveCronExpressionRequest) GetText() string {
	if r == nil {
		return ""
	}
	return r.Text
}
