// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type SSHSecurityKeysOutput struct {
	CredentialType string  `json:"credentialType"`
	Discriminator  *string `json:"discriminator,omitempty"`
}

func (s SSHSecurityKeysOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SSHSecurityKeysOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SSHSecurityKeysOutput) GetCredentialType() string {
	if s == nil {
		return ""
	}
	return s.CredentialType
}

func (s *SSHSecurityKeysOutput) GetDiscriminator() *string {
	if s == nil {
		return nil
	}
	return s.Discriminator
}
