// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TraceHeartbeatRequest struct {
	Progress *TraceProgressData `json:"progress,omitempty"`
}

func (t *TraceHeartbeatRequest) GetProgress() *TraceProgressData {
	if t == nil {
		return nil
	}
	return t.Progress
}
