// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TraceHeartbeatRequest struct {
	Progress *TraceProgressData `json:"progress,omitempty"`
}

func (o *TraceHeartbeatRequest) GetProgress() *TraceProgressData {
	if o == nil {
		return nil
	}
	return o.Progress
}
