// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateMemberRoleRequest struct {
	Role *OrgRole `json:"role,omitempty"`
}

func (u *UpdateMemberRoleRequest) GetRole() *OrgRole {
	if u == nil {
		return nil
	}
	return u.Role
}
