// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateAWSCredentialsRequest struct {
	Credentials *AWSCredential `json:"credentials,omitempty"`
}

func (o *UpdateAWSCredentialsRequest) GetCredentials() *AWSCredential {
	if o == nil {
		return nil
	}
	return o.Credentials
}
