// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0892be61b088

package shared

type UpdateAzureCredentialsRequest struct {
	Credentials AzureCredential `json:"credentials"`
}

func (u *UpdateAzureCredentialsRequest) GetCredentials() AzureCredential {
	if u == nil {
		return AzureCredential{}
	}
	return u.Credentials
}
