// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 478ab7920b77

package shared

type WfWaveMeta struct {
	Enabled *bool `json:"enabled,omitempty"`
}

func (w *WfWaveMeta) GetEnabled() *bool {
	if w == nil {
		return nil
	}
	return w.Enabled
}
