// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
)

type WorkspaceImage struct {
	AuditImageType AuditImageType `json:"auditImageType"`
	Description    *string        `json:"description,omitempty"`
	FullName       *string        `json:"fullName,omitempty"`
	Name           *string        `json:"name,omitempty"`
	Visibility     *Visibility    `json:"visibility,omitempty"`
}

func (w WorkspaceImage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspaceImage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspaceImage) GetAuditImageType() AuditImageType {
	if w == nil {
		return AuditImageType("")
	}
	return w.AuditImageType
}

func (w *WorkspaceImage) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WorkspaceImage) GetFullName() *string {
	if w == nil {
		return nil
	}
	return w.FullName
}

func (w *WorkspaceImage) GetName() *string {
	if w == nil {
		return nil
	}
	return w.Name
}

func (w *WorkspaceImage) GetVisibility() *Visibility {
	if w == nil {
		return nil
	}
	return w.Visibility
}
