// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

type Workspace struct {
	ID          *int64     `json:"id,omitempty"`
	Name        string     `json:"name"`
	FullName    string     `json:"fullName"`
	Description *string    `json:"description,omitempty"`
	Visibility  Visibility `json:"visibility"`
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
}

func (w Workspace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *Workspace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"name", "fullName", "visibility"}); err != nil {
		return err
	}
	return nil
}

func (w *Workspace) GetID() *int64 {
	if w == nil {
		return nil
	}
	return w.ID
}

func (w *Workspace) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *Workspace) GetFullName() string {
	if w == nil {
		return ""
	}
	return w.FullName
}

func (w *Workspace) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *Workspace) GetVisibility() Visibility {
	if w == nil {
		return Visibility("")
	}
	return w.Visibility
}

func (w *Workspace) GetDateCreated() *time.Time {
	if w == nil {
		return nil
	}
	return w.DateCreated
}

func (w *Workspace) GetLastUpdated() *time.Time {
	if w == nil {
		return nil
	}
	return w.LastUpdated
}
