// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/internal/utils"
	"time"
)

// WorkflowDbDto - Represents a workflow execution record.
// Contains execution status, metadata, and results from pipeline
// runs including logs and performance metrics.
type WorkflowDbDto struct {
	// Array of status messages and logs from workflow execution
	Messages []string `json:"messages,omitempty"`
	// Unique identifier for the workflow execution
	ID *string `json:"id,omitempty"`
	// Numeric identifier of the user who owns this workflow
	OwnerID *int64 `json:"ownerId,omitempty"`
	// Timestamp when the workflow was submitted for execution
	Submit *time.Time `json:"submit,omitempty"`
	// Timestamp when the workflow execution actually started
	Start *time.Time `json:"start,omitempty"`
	// Timestamp when the workflow execution completed
	Complete          *time.Time      `json:"complete,omitempty"`
	DateCreated       *time.Time      `json:"dateCreated,omitempty"`
	LastUpdated       *time.Time      `json:"lastUpdated,omitempty"`
	RunName           *string         `json:"runName,omitempty"`
	SessionID         *string         `json:"sessionId,omitempty"`
	Profile           *string         `json:"profile,omitempty"`
	WorkDir           *string         `json:"workDir,omitempty"`
	CommitID          *string         `json:"commitId,omitempty"`
	UserName          *string         `json:"userName,omitempty"`
	ScriptID          *string         `json:"scriptId,omitempty"`
	Revision          *string         `json:"revision,omitempty"`
	CommandLine       *string         `json:"commandLine,omitempty"`
	ProjectName       *string         `json:"projectName,omitempty"`
	ScriptName        *string         `json:"scriptName,omitempty"`
	LaunchID          *string         `json:"launchId,omitempty"`
	Status            *WorkflowStatus `json:"status,omitempty"`
	RequiresAttention *bool           `json:"requiresAttention,omitempty"`
	ConfigFiles       []string        `json:"configFiles,omitempty"`
	Params            map[string]any  `json:"params,omitempty"`
	ConfigText        *string         `json:"configText,omitempty"`
	Manifest          *WfManifest     `json:"manifest,omitempty"`
	Nextflow          *WfNextflow     `json:"nextflow,omitempty"`
	Stats             *WfStats        `json:"stats,omitempty"`
	ErrorMessage      *string         `json:"errorMessage,omitempty"`
	ErrorReport       *string         `json:"errorReport,omitempty"`
	Deleted           *bool           `json:"deleted,omitempty"`
	ProjectDir        *string         `json:"projectDir,omitempty"`
	HomeDir           *string         `json:"homeDir,omitempty"`
	Container         *string         `json:"container,omitempty"`
	Repository        *string         `json:"repository,omitempty"`
	ContainerEngine   *string         `json:"containerEngine,omitempty"`
	ScriptFile        *string         `json:"scriptFile,omitempty"`
	LaunchDir         *string         `json:"launchDir,omitempty"`
	Duration          *int64          `json:"duration,omitempty"`
	ExitStatus        *int            `json:"exitStatus,omitempty"`
	Resume            *bool           `json:"resume,omitempty"`
	Success           *bool           `json:"success,omitempty"`
}

func (w WorkflowDbDto) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkflowDbDto) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WorkflowDbDto) GetMessages() []string {
	if o == nil {
		return nil
	}
	return o.Messages
}

func (o *WorkflowDbDto) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *WorkflowDbDto) GetOwnerID() *int64 {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

func (o *WorkflowDbDto) GetSubmit() *time.Time {
	if o == nil {
		return nil
	}
	return o.Submit
}

func (o *WorkflowDbDto) GetStart() *time.Time {
	if o == nil {
		return nil
	}
	return o.Start
}

func (o *WorkflowDbDto) GetComplete() *time.Time {
	if o == nil {
		return nil
	}
	return o.Complete
}

func (o *WorkflowDbDto) GetDateCreated() *time.Time {
	if o == nil {
		return nil
	}
	return o.DateCreated
}

func (o *WorkflowDbDto) GetLastUpdated() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUpdated
}

func (o *WorkflowDbDto) GetRunName() *string {
	if o == nil {
		return nil
	}
	return o.RunName
}

func (o *WorkflowDbDto) GetSessionID() *string {
	if o == nil {
		return nil
	}
	return o.SessionID
}

func (o *WorkflowDbDto) GetProfile() *string {
	if o == nil {
		return nil
	}
	return o.Profile
}

func (o *WorkflowDbDto) GetWorkDir() *string {
	if o == nil {
		return nil
	}
	return o.WorkDir
}

func (o *WorkflowDbDto) GetCommitID() *string {
	if o == nil {
		return nil
	}
	return o.CommitID
}

func (o *WorkflowDbDto) GetUserName() *string {
	if o == nil {
		return nil
	}
	return o.UserName
}

func (o *WorkflowDbDto) GetScriptID() *string {
	if o == nil {
		return nil
	}
	return o.ScriptID
}

func (o *WorkflowDbDto) GetRevision() *string {
	if o == nil {
		return nil
	}
	return o.Revision
}

func (o *WorkflowDbDto) GetCommandLine() *string {
	if o == nil {
		return nil
	}
	return o.CommandLine
}

func (o *WorkflowDbDto) GetProjectName() *string {
	if o == nil {
		return nil
	}
	return o.ProjectName
}

func (o *WorkflowDbDto) GetScriptName() *string {
	if o == nil {
		return nil
	}
	return o.ScriptName
}

func (o *WorkflowDbDto) GetLaunchID() *string {
	if o == nil {
		return nil
	}
	return o.LaunchID
}

func (o *WorkflowDbDto) GetStatus() *WorkflowStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *WorkflowDbDto) GetRequiresAttention() *bool {
	if o == nil {
		return nil
	}
	return o.RequiresAttention
}

func (o *WorkflowDbDto) GetConfigFiles() []string {
	if o == nil {
		return nil
	}
	return o.ConfigFiles
}

func (o *WorkflowDbDto) GetParams() map[string]any {
	if o == nil {
		return nil
	}
	return o.Params
}

func (o *WorkflowDbDto) GetConfigText() *string {
	if o == nil {
		return nil
	}
	return o.ConfigText
}

func (o *WorkflowDbDto) GetManifest() *WfManifest {
	if o == nil {
		return nil
	}
	return o.Manifest
}

func (o *WorkflowDbDto) GetNextflow() *WfNextflow {
	if o == nil {
		return nil
	}
	return o.Nextflow
}

func (o *WorkflowDbDto) GetStats() *WfStats {
	if o == nil {
		return nil
	}
	return o.Stats
}

func (o *WorkflowDbDto) GetErrorMessage() *string {
	if o == nil {
		return nil
	}
	return o.ErrorMessage
}

func (o *WorkflowDbDto) GetErrorReport() *string {
	if o == nil {
		return nil
	}
	return o.ErrorReport
}

func (o *WorkflowDbDto) GetDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.Deleted
}

func (o *WorkflowDbDto) GetProjectDir() *string {
	if o == nil {
		return nil
	}
	return o.ProjectDir
}

func (o *WorkflowDbDto) GetHomeDir() *string {
	if o == nil {
		return nil
	}
	return o.HomeDir
}

func (o *WorkflowDbDto) GetContainer() *string {
	if o == nil {
		return nil
	}
	return o.Container
}

func (o *WorkflowDbDto) GetRepository() *string {
	if o == nil {
		return nil
	}
	return o.Repository
}

func (o *WorkflowDbDto) GetContainerEngine() *string {
	if o == nil {
		return nil
	}
	return o.ContainerEngine
}

func (o *WorkflowDbDto) GetScriptFile() *string {
	if o == nil {
		return nil
	}
	return o.ScriptFile
}

func (o *WorkflowDbDto) GetLaunchDir() *string {
	if o == nil {
		return nil
	}
	return o.LaunchDir
}

func (o *WorkflowDbDto) GetDuration() *int64 {
	if o == nil {
		return nil
	}
	return o.Duration
}

func (o *WorkflowDbDto) GetExitStatus() *int {
	if o == nil {
		return nil
	}
	return o.ExitStatus
}

func (o *WorkflowDbDto) GetResume() *bool {
	if o == nil {
		return nil
	}
	return o.Resume
}

func (o *WorkflowDbDto) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}
