// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type WorkflowQueryAttribute string

const (
	WorkflowQueryAttributeOptimized WorkflowQueryAttribute = "optimized"
	WorkflowQueryAttributeLabels    WorkflowQueryAttribute = "labels"
	WorkflowQueryAttributeMessages  WorkflowQueryAttribute = "messages"
	WorkflowQueryAttributeMinimal   WorkflowQueryAttribute = "minimal"
)

func (e WorkflowQueryAttribute) ToPointer() *WorkflowQueryAttribute {
	return &e
}
func (e *WorkflowQueryAttribute) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "optimized":
		fallthrough
	case "labels":
		fallthrough
	case "messages":
		fallthrough
	case "minimal":
		*e = WorkflowQueryAttribute(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WorkflowQueryAttribute: %v", v)
	}
}
