workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Seqera API:
        inputs:
            - location: schemas/seqera-final.yaml
        overlays:
            - location: schemas/overlay_new.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/seqera/seqera/seqera-api
targets:
    seqera:
        target: terraform
        source: Seqera API
