workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Seqera API:
        inputs:
            - location: specs/seqera-api-1.45.0.yaml
        overlays:
            - location: overlays/speakeasy.yaml
            - location: overlays/required.yaml
            - location: overlays/schema-descriptions.yaml
            - location: overlays/schema-field-descriptions.yaml
            - location: overlays/request-examples.yaml
            - location: overlays/validators.yaml
            - location: overlays/retry.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/seqera/seqera/seqera-api
targets:
    seqera:
        target: terraform
        source: Seqera API
