workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Seqera API:
        inputs:
            - location: specs/seqera-api-cloud.yaml
        overlays:
            - location: overlays/api-description.yaml
            - location: overlays/speakeasy.yaml
            - location: overlays/required.yaml
            - location: overlays/schema-descriptions.yaml
            - location: overlays/schema-field-descriptions.yaml
            - location: overlays/request-examples.yaml
            - location: overlays/request-body-fixes.yaml
            - location: overlays/regex-fixes.yaml
            - location: overlays/deduplicate-enums.yaml
            - location: overlays/tag-and-schema-cleanup.yaml
            - location: overlays/validators.yaml
            - location: overlays/retry.yaml
            - location: overlays/datalinks.yaml
            - location: overlays/actions.yaml
            - location: overlays/credentials.yaml
            - location: overlays/azure-credentials.yaml
            - location: overlays/gcp-credentials.yaml
            - location: overlays/compute-env.yaml
            - location: overlays/aws-compute-env.yaml
            - location: overlays/datasets.yaml
            - location: overlays/labels.yaml
            - location: overlays/orgs.yaml
            - location: overlays/pipeline-secrets.yaml
            - location: overlays/pipelines.yaml
            - location: overlays/studios.yaml
            - location: overlays/teams.yaml
            - location: overlays/tokens.yaml
            - location: overlays/managed-identities.yaml
            - location: overlays/managed-credentials.yaml
            - location: overlays/organization-member.yaml
            - location: overlays/workspace-participant.yaml
            - location: overlays/workflows-resource.yaml
            - location: overlays/workspaces.yaml
            - location: overlays/users.yaml
            - location: overlays/schema-fixes.yaml
            - location: overlays/primary-compute-env.yaml
            - location: overlays/aws-credentials.yaml
            - location: overlays/method-names.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/seqera/seqera/seqera-api
targets:
    seqera:
        target: terraform
        source: Seqera API
