locals {
  work_dir = "gs://terraform-provider-testing"
}

## Organizations
resource "seqera_orgs" "test_org" {
  description = "testing org for the terraform provider - Azure"
  full_name   = "seqera_test_shahbaz_tf_provider_gcp"
  name        = "seqera_test_shahbaz_tf_provider_gcp"
}

## Workspaces
resource  "seqera_workspace" "my_workspace" {
  description = "A test workspace created with Terraform for GCP"
  name        = "test-workspace-tf-gcp"
  full_name   = "Test Workspace for Terraform Provider"
  org_id     = resource.seqera_orgs.test_org.org_id
  visibility = "PRIVATE"
}

## Datasets
resource "seqera_datasets" "my_datasets" {
  description  = "Terraform created dataset"
  name         = "terraform-dataset"
  workspace_id = resource.seqera_workspace.my_workspace.id
}

locals {
  service_account_key = file("${path.module}/service-account-key.json")
}

## Credentials
resource "seqera_credential" "gcp_credential" {

  name          = "test_credential"
  provider_type = "google"
  workspace_id  = resource.seqera_workspace.my_workspace.id
  description   = "AWS credentials generated by terraform"    
  keys = {
    google = {
        data = local.service_account_key
    }
      
  }
  
}
