data "seqera_user" "my_user" {
  user_id = 7672
}

data "seqera_user_workspaces" "test" {
  user_id = 7672
}

data "seqera_current_user" "my_currentuser" {
}

output "user_id" {
  value = data.seqera_user.my_user.user_id
}


output "current_user_id" {
  value = data.seqera_current_user.my_currentuser
}
# output "test_workspace" {
#   value = data.seqera_user_workspaces.test
# }


resource "seqera_credential" "test_credential" {

  name          = "test_credential"
  provider_type = "aws"
  workspace_id  = 49242724423913
  description   = "AWS credentials generated by terraform"    
  keys = {
    aws = {
      access_key      = "Test"
      secret_key      = "Test"
      # assume_role_arn = "arn:aws:iam::123456789012:role/MyRole"  # Optional
    }
  }
}
