// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/operations"
	"github.com/seqeralabs/terraform-provider-seqera/internal/sdk/models/shared"
)

func (r *BitbucketCredentialDataSourceModel) RefreshFromSharedBitbucketCredentialKeysOutput(ctx context.Context, resp *shared.BitbucketCredentialKeysOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	r.Username = types.StringValue(resp.Username)

	return diags
}

func (r *BitbucketCredentialDataSourceModel) RefreshFromSharedBitbucketCredentialOutput(ctx context.Context, resp *shared.BitbucketCredentialOutput) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ID = types.StringPointerValue(resp.ID)
		diags.Append(r.RefreshFromSharedBitbucketCredentialKeysOutput(ctx, &resp.Keys)...)

		if diags.HasError() {
			return diags
		}

		r.Name = types.StringValue(resp.Name)
		if resp.ProviderType != nil {
			r.ProviderType = types.StringValue(string(*resp.ProviderType))
		} else {
			r.ProviderType = types.StringNull()
		}
	}

	return diags
}

func (r *BitbucketCredentialDataSourceModel) RefreshFromSharedDescribeBitbucketCredentialsResponse(ctx context.Context, resp *shared.DescribeBitbucketCredentialsResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedBitbucketCredentialOutput(ctx, resp.Credentials)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *BitbucketCredentialDataSourceModel) ToOperationsDescribeBitbucketCredentialsRequest(ctx context.Context) (*operations.DescribeBitbucketCredentialsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var credentialsID string
	credentialsID = r.CredentialsID.ValueString()

	workspaceID := new(int64)
	if !r.WorkspaceID.IsUnknown() && !r.WorkspaceID.IsNull() {
		*workspaceID = r.WorkspaceID.ValueInt64()
	} else {
		workspaceID = nil
	}
	out := operations.DescribeBitbucketCredentialsRequest{
		CredentialsID: credentialsID,
		WorkspaceID:   workspaceID,
	}

	return &out, diags
}
