// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2f12352aeeaf

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AzureReposCredentials struct {
	Password types.String `tfsdk:"password"`
	Token    types.String `tfsdk:"token"`
	Username types.String `tfsdk:"username"`
}
