// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Credentials struct {
	BaseURL       types.String        `tfsdk:"base_url"`
	Category      types.String        `tfsdk:"category"`
	CredentialsID types.String        `tfsdk:"credentials_id"`
	DateCreated   types.String        `tfsdk:"date_created"`
	Deleted       types.Bool          `tfsdk:"deleted"`
	Description   types.String        `tfsdk:"description"`
	Keys          *SecurityKeysOutput `tfsdk:"keys"`
	LastUpdated   types.String        `tfsdk:"last_updated"`
	LastUsed      types.String        `tfsdk:"last_used"`
	Name          types.String        `tfsdk:"name"`
	ProviderType  types.String        `tfsdk:"provider_type"`
}
