// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 28687149fbb5

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type CronActionRequest struct {
	Expression types.String `tfsdk:"expression"`
	Preset     types.String `tfsdk:"preset"`
	Timezone   types.String `tfsdk:"timezone"`
}
