// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DataStudioDto struct {
	ActiveConnections      []ActiveConnection             `tfsdk:"active_connections"`
	BaseImage              types.String                   `tfsdk:"base_image"`
	ComputeEnv             *DataStudioComputeEnvDto       `tfsdk:"compute_env"`
	Configuration          *DataStudioConfiguration       `tfsdk:"configuration"`
	CustomImage            types.Bool                     `tfsdk:"custom_image"`
	DateCreated            types.String                   `tfsdk:"date_created"`
	Description            types.String                   `tfsdk:"description"`
	EffectiveLifespanHours types.Int32                    `tfsdk:"effective_lifespan_hours"`
	IsPrivate              types.Bool                     `tfsdk:"is_private"`
	Labels                 []LabelDbDto                   `tfsdk:"labels"`
	LastStarted            types.String                   `tfsdk:"last_started"`
	LastUpdated            types.String                   `tfsdk:"last_updated"`
	MountedDataLinks       []DataLinkDto                  `tfsdk:"mounted_data_links"`
	Name                   types.String                   `tfsdk:"name"`
	ParentCheckpoint       *DataStudioDtoParentCheckpoint `tfsdk:"parent_checkpoint"`
	Progress               []DataStudioProgressStep       `tfsdk:"progress"`
	SessionID              types.String                   `tfsdk:"session_id"`
	StatusInfo             *DataStudioStatusInfo          `tfsdk:"status_info"`
	StudioURL              types.String                   `tfsdk:"studio_url"`
	Template               *DataStudioTemplate            `tfsdk:"template"`
	User                   *StudioUser                    `tfsdk:"user"`
	WaveBuildURL           types.String                   `tfsdk:"wave_build_url"`
	WorkspaceID            types.Int64                    `tfsdk:"workspace_id"`
}
