// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DataStudioComputeEnvDto struct {
	CredentialsID types.String `tfsdk:"credentials_id"`
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	Platform      types.String `tfsdk:"platform"`
	Region        types.String `tfsdk:"region"`
	WorkDir       types.String `tfsdk:"work_dir"`
}
