// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a6d4944159d4

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GitHubCredentials struct {
	Password types.String `tfsdk:"password"`
	Token    types.String `tfsdk:"token"`
	Username types.String `tfsdk:"username"`
}
