// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f49ee3b89983

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GithubActionConfig struct {
	Discriminator types.String `tfsdk:"discriminator"`
}
