// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GoogleCredentialInput struct {
	BaseURL       types.String       `tfsdk:"base_url"`
	Category      types.String       `tfsdk:"category"`
	CredentialsID types.String       `tfsdk:"credentials_id"`
	Description   types.String       `tfsdk:"description"`
	Keys          GoogleSecurityKeys `tfsdk:"keys"`
	Name          types.String       `tfsdk:"name"`
	ProviderType  types.String       `tfsdk:"provider_type"`
}
