// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GoogleCloudConfig struct {
	Arm64Enabled        types.Bool                                   `tfsdk:"arm64_enabled"`
	BootDiskSizeGb      types.Int32                                  `tfsdk:"boot_disk_size_gb"`
	EnableFusion        types.Bool                                   `tfsdk:"enable_fusion"`
	EnableWave          types.Bool                                   `tfsdk:"enable_wave"`
	Environment         []ConfigEnvVariable                          `tfsdk:"environment"`
	ForgedResources     []map[string]GoogleCloudConfigForgedResource `tfsdk:"forged_resources"`
	GpuEnabled          types.Bool                                   `tfsdk:"gpu_enabled"`
	ImageID             types.String                                 `tfsdk:"image_id"`
	InstanceType        types.String                                 `tfsdk:"instance_type"`
	NextflowConfig      types.String                                 `tfsdk:"nextflow_config"`
	PostRunScript       types.String                                 `tfsdk:"post_run_script"`
	PreRunScript        types.String                                 `tfsdk:"pre_run_script"`
	ProjectID           types.String                                 `tfsdk:"project_id"`
	Region              types.String                                 `tfsdk:"region"`
	ServiceAccountEmail types.String                                 `tfsdk:"service_account_email"`
	WorkDir             types.String                                 `tfsdk:"work_dir"`
	Zone                types.String                                 `tfsdk:"zone"`
}
