// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package mapvalidators

import (
	"context"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

var _ validator.Map = MapGoogleResourceLabelsValidatorValidator{}

// MapGoogleResourceLabelsValidatorValidator validates the config.labels map on
// Google compute environments. These are static Google Cloud resource labels
// applied to the compute environment at creation time — they are NOT Seqera
// resource labels and are NOT interpolated at workflow submission time.
//
// A common mistake is to place dynamic resource label placeholders
// (${sessionId}, ${workflowId}, ${userName}) here. Terraform accepts them and
// the compute environment is created, but the placeholder is stored as a
// literal Google Cloud label value. Because ${...} is not a valid Google Cloud
// label value, every workflow launched on the compute environment fails to
// start with "Bad Request". This validator catches that mistake at plan time
// and points users at the supported `label_ids` path instead.
type MapGoogleResourceLabelsValidatorValidator struct{}

// labelDynamicPlaceholderPattern matches a dynamic resource label placeholder
// such as ${sessionId}.
var labelDynamicPlaceholderPattern = regexp.MustCompile(`\$\{[^}]*\}`)

// Description describes the validation in plain text formatting.
func (v MapGoogleResourceLabelsValidatorValidator) Description(_ context.Context) string {
	return "Google Cloud resource label values cannot contain dynamic placeholders such as ${sessionId}"
}

// MarkdownDescription describes the validation in Markdown formatting.
func (v MapGoogleResourceLabelsValidatorValidator) MarkdownDescription(ctx context.Context) string {
	return v.Description(ctx)
}

// Validate performs the validation.
func (v MapGoogleResourceLabelsValidatorValidator) ValidateMap(ctx context.Context, req validator.MapRequest, resp *validator.MapResponse) {
	// Only validate the attribute configuration value if it is known.
	if req.ConfigValue.IsNull() || req.ConfigValue.IsUnknown() {
		return
	}

	for key, elem := range req.ConfigValue.Elements() {
		if elem.IsNull() || elem.IsUnknown() {
			continue
		}
		// The map element string is quoted (e.g. "${sessionId}"); matching the
		// placeholder pattern against it is unaffected by the surrounding quotes.
		if labelDynamicPlaceholderPattern.MatchString(elem.String()) {
			resp.Diagnostics.AddAttributeError(
				req.Path,
				"Invalid Google Cloud Resource Label Value",
				fmt.Sprintf("The label '%s' uses a dynamic placeholder, but config.labels holds static Google Cloud "+
					"resource labels applied at compute environment creation time, not Seqera dynamic resource labels. "+
					"A placeholder such as ${sessionId} is not a valid Google Cloud label value and will cause every "+
					"workflow launched on this compute environment to fail to start with \"Bad Request\".\n\n"+
					"To use dynamic resource labels (${sessionId}, ${workflowId}, ${userName}), create them as "+
					"seqera_labels resources (resource = true) and attach them through the compute environment's "+
					"label_ids field instead.", key),
			)
		}
	}
}

// GoogleResourceLabelsValidator returns a validator which rejects dynamic
// resource label placeholders in a Google compute environment's config.labels
// map, since those are static Google Cloud labels rather than Seqera dynamic
// resource labels.
func GoogleResourceLabelsValidator() validator.Map {
	return MapGoogleResourceLabelsValidatorValidator{}
}
