name: Go Lint and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.24'

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Install golangci
      run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@e9d425110dcd46293652c5981b0a479d091d9f88 #v2.2.2

    - name: Run golangci lint
      run: golangci-lint run

    - name: Build
      run: go build -v ./...

    # - name: Run tests
    #   run: go test -v ./...
