name: Speakeasy Lint and Generate

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    paths:
      - 'schemas/**'
      - '.speakeasy/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  speakeasy-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.24'

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@b8ec13ce4d00445d75da053c47498e6f9ec5d7d6 # v0.6.1

    - name: Install Speakeasy
      run: |
        curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Verify Speakeasy Installation
      run: speakeasy --version

    - name: Lint OpenAPI Schema
      run: |
        speakeasy lint openapi -s .speakeasy/out.openapi.yaml > lint_output.txt 2>&1 || true
        cat lint_output.txt

    - name: Generate Speakeasy Lint Comment
      if: github.event_name == 'pull_request'
      run: |
        # Extract the summary line from lint output
        SUMMARY=$(grep -o '[0-9]\+ errors\?, [0-9]\+ warnings\?, [0-9]\+ hints' lint_output.txt || echo "Summary not found")

        echo "## Speakeasy Lint Results: $SUMMARY" > lint_comment.md
        echo "" >> lint_comment.md
        echo "<details>" >> lint_comment.md
        echo "<summary>Click to expand lint output</summary>" >> lint_comment.md
        echo "" >> lint_comment.md
        echo "\`\`\`" >> lint_comment.md
        cat lint_output.txt >> lint_comment.md
        echo "\`\`\`" >> lint_comment.md
        echo "" >> lint_comment.md
        echo "</details>" >> lint_comment.md
        echo "" >> lint_comment.md
        echo "Lint completed at: $(date)" >> lint_comment.md

    - name: Comment PR with Speakeasy Lint Results
      if: github.event_name == 'pull_request'
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      with:
        message-path: lint_comment.md
        message-id: speakeasy-lint

    - name: Generate Provider Code (Dry Run)
      run: speakeasy run --skip-versioning
      env:
        SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}

    - name: Check for uncommitted changes
      run: |
        git diff --exit-code -- . ':!.speakeasy/workflow.lock' || {
          echo "Generated code differs from committed code. Please run 'speakeasy run --skip-versioning' and commit the changes."
          exit 1
        }
